/* Subject Module texts and questions — the second batch, added with the per-subject tests.
   Each entry: { id, area, title, domain, text (HTML), qs: [{ t, q, o[4], a, e, tip }] }.
   `a` is the index of the correct option; options are shuffled at runtime.
   See CONTRIBUTING.md for how to add one. */
const MORE=[
{id:'series',area:'math',title:'Arithmetic and Geometric Sequences',domain:'Mathematics',text:`<p>In an <b>arithmetic sequence</b>, each term is obtained by adding a constant difference d: a<sub>n</sub> = a<sub>1</sub> + (n − 1)·d. The sum of the first n terms is S<sub>n</sub> = n·(a<sub>1</sub> + a<sub>n</sub>) ÷ 2.</p><p>In a <b>geometric sequence</b>, each term is obtained by multiplying by a constant ratio q: a<sub>n</sub> = a<sub>1</sub>·q<sup>n−1</sup>. The sum of the first n terms is S<sub>n</sub> = a<sub>1</sub>·(q<sup>n</sup> − 1) ÷ (q − 1) for q ≠ 1.</p><p>If |q| &lt; 1, the terms shrink toward zero and the sum of <i>all</i> infinitely many terms approaches a finite value: S = a<sub>1</sub> ÷ (1 − q).</p>`,
qs:[
{t:'calc',q:'What is the 5th term of the sequence 3, 7, 11, …?',o:['15','19','20','23'],a:1,e:'d = 4; a₅ = 3 + 4·4 = 19.',tip:'Term n = first + (n − 1) steps. Count the steps, not the terms.'},
{t:'calc',q:'What is the sum 1 + 2 + 3 + … + 100?',o:['5,000','5,050','5,100','10,100'],a:1,e:'S = 100·(1 + 100) ÷ 2 = 5,050.',tip:'Gauss pairing: number of terms × average of first and last.'},
{t:'calc',q:'What is the 5th term of the geometric sequence 2, 6, 18, …?',o:['54','96','162','486'],a:2,e:'q = 3; a₅ = 2·3⁴ = 2·81 = 162.',tip:'Exponent is n − 1: the 5th term has 4 multiplications.'},
{t:'calc',q:'What value does the infinite sum 8 + 4 + 2 + 1 + … approach?',o:['14','16','32','It grows without limit.'],a:1,e:'a₁ = 8, q = ½: S = 8 ÷ (1 − ½) = 16.',tip:'Infinite geometric sum = first term ÷ (1 − ratio), only if |ratio| < 1.'},
{t:'multi',q:'Which statements are correct?<br>I. 5, 10, 20, 40 is a geometric sequence.<br>II. 1, 4, 9, 16 is an arithmetic sequence.<br>III. A geometric sequence with q = −1 alternates its sign.',o:['Only I','I and III','II and III','I, II and III'],a:1,e:'I: ratio 2 ✓. II: differences 3, 5, 7 are not constant ✗. III: 1, −1, 1, … ✓.',tip:'For I/II/III questions, judge each statement separately, then match the combination. Eliminate every option containing a false statement.'},
{t:'transfer',q:'A student saves €100 in the first month and each month €20 more than in the month before. How much has she saved in total after 12 months?',o:['€1,320','€2,400','€2,520','€3,840'],a:2,e:'a₁₂ = 100 + 11·20 = 320; S = 12·(100 + 320) ÷ 2 = 2,520.',tip:'Recognise the hidden sequence in a word problem ("each month €20 more" = arithmetic, "each year 5 % more" = geometric).'}
]},
{id:'deriv',area:'math',title:'Rates of Change and Optimisation',domain:'Mathematics',text:`<p>The <b>derivative</b> f′(x) gives the slope of a function at the point x, i.e. its instantaneous rate of change. Basic rules: the derivative of x<sup>n</sup> is n·x<sup>n−1</sup>; constant factors are kept; the derivative of a sum is the sum of the derivatives; the derivative of a constant is 0.</p><p>If f′(x) &gt; 0 on an interval, f is increasing there; if f′(x) &lt; 0, f is decreasing. At a (local) maximum or minimum of a smooth function, f′(x) = 0. The <b>second derivative</b> decides the type: f″(x) &lt; 0 indicates a maximum, f″(x) &gt; 0 a minimum. However, f′(x) = 0 alone does not guarantee an extremum.</p><p>In economics, the derivative of the cost function C(q) is called the <b>marginal cost</b>: the approximate cost of producing one additional unit.</p>`,
qs:[
{t:'calc',q:'f(x) = 3x² + 2x. What is f′(2)?',o:['8','12','14','16'],a:2,e:'f′(x) = 6x + 2; f′(2) = 14.',tip:'Power rule: bring the exponent down, reduce it by one.'},
{t:'concept',q:'On an interval, f′(x) > 0 for all x. What follows?',o:['f is positive on the interval.','f is increasing on the interval.','f has a maximum on the interval.','f is constant on the interval.'],a:1,e:'A positive slope means the function values rise; it says nothing about the sign of f itself.',tip:'Don\'t confuse the sign of f′ (direction) with the sign of f (value).'},
{t:'transfer',q:'A rectangle has a perimeter of 80 m, so its area is A(x) = x·(40 − x). What is the largest possible area?',o:['200 m²','400 m²','800 m²','1,600 m²'],a:1,e:'A′(x) = 40 − 2x = 0 ⇒ x = 20; A = 20·20 = 400 m².',tip:'For a fixed perimeter, the square has the largest area — a quick sanity check.'},
{t:'concept',q:'Which statement about f(x) = x³ is correct?',o:['x = 0 is a maximum.','x = 0 is a minimum.','f′(0) = 0, yet x = 0 is neither a maximum nor a minimum.','f′(0) = 3.'],a:2,e:'f′(x) = 3x², so f′(0) = 0, but f increases on both sides of 0 (a saddle point).',tip:'f′ = 0 is necessary, not sufficient, for an extremum. The text often hints at such traps with "however".'},
{t:'calc',q:'A cost function is C(q) = 100 + 4q + 0.5q². What is the marginal cost at q = 10?',o:['4','10','14','150'],a:2,e:'C′(q) = 4 + q; C′(10) = 14.',tip:'Fixed costs (the constant 100) disappear when you differentiate.'},
{t:'except',q:'All of the following statements about f(x) = −x² + 6x are true EXCEPT:',o:['f has its maximum at x = 3.','f′(x) = −2x + 6.','The maximum value of f is 9.','f is increasing for x > 3.'],a:3,e:'For x > 3, f′(x) < 0, so f is decreasing. f(3) = −9 + 18 = 9.',tip:'EXCEPT questions: three options are true. Test each one and pick the one that fails.'}
]},
{id:'combi',area:'math',title:'Counting and Combinatorics',domain:'Mathematics',text:`<p>Combinatorics counts possibilities. By the <b>multiplication principle</b>, if one choice has m options and a second, independent choice has n options, there are m·n combinations.</p><table><tr><th>Situation</th><th>Number of possibilities</th></tr><tr><td>Arrange n different objects in a row</td><td>n! = n·(n−1)·…·1</td></tr><tr><td>Ordered selection of k from n (no repetition)</td><td>n! ÷ (n−k)!</td></tr><tr><td>Unordered selection of k from n (no repetition)</td><td>C(n,k) = n! ÷ (k!·(n−k)!)</td></tr><tr><td>Ordered selection of k from n with repetition</td><td>n<sup>k</sup></td></tr></table><p>Note that C(n,k) = C(n, n−k): choosing k objects to take is the same as choosing n−k objects to leave. If all outcomes are equally likely, a probability equals the number of favourable outcomes divided by the number of possible outcomes.</p>`,
qs:[
{t:'calc',q:'A person has 3 shirts and 4 pairs of trousers. How many different outfits are possible?',o:['7','12','24','81'],a:1,e:'3 · 4 = 12.',tip:'"And" between independent choices → multiply.'},
{t:'calc',q:'In how many different orders can 5 different books be placed on a shelf?',o:['25','60','120','3,125'],a:2,e:'5! = 120.',tip:'Know by heart: 3! = 6, 4! = 24, 5! = 120, 6! = 720.'},
{t:'calc',q:'A committee of 2 people is chosen from 6 candidates. How many different committees are possible?',o:['12','15','30','36'],a:1,e:'C(6,2) = 6·5 ÷ 2 = 15.',tip:'Order irrelevant → divide the ordered count by k!.'},
{t:'data',q:'A PIN consists of 4 digits (0–9); digits may repeat. How many PINs are possible? Use the table.',o:['40','5,040','10,000','40,320'],a:2,e:'Ordered with repetition: 10⁴ = 10,000.',tip:'Decide two things first: does order matter? is repetition allowed? Then pick the table row.'},
{t:'concept',q:'How do C(10,3) and C(10,7) compare?',o:['C(10,3) is larger.','They are equal.','C(10,7) is larger.','They cannot be compared without calculating.'],a:1,e:'C(n,k) = C(n,n−k), both equal 120.',tip:'Symmetry saves time: choosing who goes = choosing who stays.'},
{t:'calc',q:'In a game, 2 different numbers are drawn from 1 to 10 (order irrelevant). What is the probability of guessing both correctly with one ticket?',o:['1/100','1/90','1/45','1/20'],a:2,e:'C(10,2) = 45 equally likely pairs ⇒ 1/45.',tip:'Probability = 1 ÷ (number of equally likely outcomes) when only one outcome wins.'}
]},
{id:'normal',area:'stats',title:'The Normal Distribution and Significance Tests',domain:'Statistics',text:`<p>Many measurements follow a <b>normal distribution</b>, a symmetric bell curve described by its mean μ and standard deviation σ. The <b>68–95–99.7 rule</b> states that about 68 % of values lie within μ ± 1σ, 95 % within μ ± 2σ and 99.7 % within μ ± 3σ. The <b>z-score</b> z = (x − μ) ÷ σ states how many standard deviations a value lies from the mean.</p><svg viewBox="0 0 320 120" width="100%" style="max-width:360px" role="img" aria-label="Bell curve with bands at one and two standard deviations"><path d="M10,110 C70,110 110,15 160,15 C210,15 250,110 310,110" fill="none" stroke="currentColor" stroke-width="2"/><g stroke="currentColor" stroke-dasharray="3 3" opacity=".6"><line x1="160" y1="15" x2="160" y2="110"/><line x1="122" y1="50" x2="122" y2="110"/><line x1="198" y1="50" x2="198" y2="110"/><line x1="88" y1="92" x2="88" y2="110"/><line x1="232" y1="92" x2="232" y2="110"/></g><g font-size="10" fill="currentColor" text-anchor="middle"><text x="160" y="119">μ</text><text x="122" y="119">−1σ</text><text x="198" y="119">+1σ</text><text x="88" y="119">−2σ</text><text x="232" y="119">+2σ</text><text x="160" y="70">68 %</text></g></svg><p>In a <b>significance test</b>, a null hypothesis H<sub>0</sub> (e.g. "the drug has no effect") is tested. The <b>p-value</b> is the probability of obtaining data at least as extreme as observed if H<sub>0</sub> were true. If p is smaller than the chosen significance level α (often 0.05), H<sub>0</sub> is rejected. Rejecting a true H<sub>0</sub> is a <b>type I error</b>; failing to reject a false H<sub>0</sub> is a <b>type II error</b>. The standard error of a sample mean is σ ÷ √n.</p>`,
qs:[
{t:'data',q:'IQ scores are normally distributed with μ = 100 and σ = 15. Roughly what share of people score between 85 and 115?',o:['34 %','50 %','68 %','95 %'],a:2,e:'85–115 is μ ± 1σ ⇒ about 68 %.',tip:'Convert the interval into "how many σ" first, then apply 68–95–99.7.'},
{t:'calc',q:'What is the z-score of an IQ of 130?',o:['1.3','2','3','30'],a:1,e:'(130 − 100) ÷ 15 = 2.',tip:'z = distance from the mean ÷ σ.'},
{t:'calc',q:'Roughly what share of people have an IQ above 130?',o:['2.5 %','5 %','16 %','34 %'],a:0,e:'95 % lie within ±2σ, so 5 % lie outside, half of it above: 2.5 %.',tip:'Symmetry: split the outside share in two for a one-sided question.'},
{t:'concept',q:'A study reports p = 0.03 with α = 0.05. What is the correct conclusion?',o:['H₀ is proven true.','H₀ is rejected.','H₀ cannot be rejected.','The probability that H₀ is true is 3 %.'],a:1,e:'p < α ⇒ reject H₀. The p-value is not the probability that H₀ is true.',tip:'"p low, H₀ must go."'},
{t:'concept',q:'A new drug has no real effect, but the study concludes that it works. What has happened?',o:['A type I error','A type II error','A correct decision','A sampling bias by definition'],a:0,e:'A true H₀ ("no effect") was rejected.',tip:'Type I = false alarm; Type II = missed detection.'},
{t:'transfer',q:'The sample size of a study is increased from 25 to 100. What happens to the standard error of the mean?',o:['It quadruples.','It doubles.','It halves.','It is divided by four.'],a:2,e:'σ/√25 = σ/5 → σ/√100 = σ/10: halved.',tip:'Anything "∝ 1/√n": 4× the data → half the error.'}
]},
{id:'genetics',area:'chembio',title:'Mendelian Inheritance',domain:'Biology',text:`<p>Many traits are determined by a gene with two variants (<b>alleles</b>). Each individual carries two alleles, one from each parent. A <b>dominant</b> allele (A) determines the appearance (<b>phenotype</b>) whenever it is present; a <b>recessive</b> allele (a) only shows in the genotype aa. Individuals with two identical alleles are <b>homozygous</b> (AA, aa), others <b>heterozygous</b> (Aa).</p><p>Each parent passes on one of its two alleles with equal probability. The possible offspring can be shown in a <b>Punnett square</b>:</p><table><tr><th>Aa × Aa</th><th>A</th><th>a</th></tr><tr><th>A</th><td>AA</td><td>Aa</td></tr><tr><th>a</th><td>Aa</td><td>aa</td></tr></table><p>This gives the genotype ratio 1 AA : 2 Aa : 1 aa and the phenotype ratio 3 dominant : 1 recessive. In a <b>test cross</b>, an individual with the dominant phenotype is crossed with aa to reveal its genotype. For two independently inherited genes (AaBb × AaBb), the phenotype ratio is 9 : 3 : 3 : 1.</p>`,
qs:[
{t:'data',q:'Two heterozygous parents (Aa × Aa) have a child. What is the probability that the child shows the recessive phenotype?',o:['0 %','25 %','50 %','75 %'],a:1,e:'Only aa (1 of 4 cells) is recessive.',tip:'Draw the 2×2 square in your head: four equally likely cells.'},
{t:'calc',q:'What share of the offspring of Aa × aa shows the dominant phenotype?',o:['25 %','50 %','75 %','100 %'],a:1,e:'Offspring: Aa, Aa, aa, aa ⇒ 50 % dominant.',tip:'aa can only pass on a, so the other parent alone decides.'},
{t:'calc',q:'Among the offspring of Aa × Aa that show the dominant phenotype, what fraction is heterozygous?',o:['1/4','1/2','2/3','3/4'],a:2,e:'Dominant: AA, Aa, Aa ⇒ 2 of 3 are Aa.',tip:'Conditional question: shrink the denominator to the group named ("among those who …").'},
{t:'transfer',q:'A plant with the dominant phenotype is test-crossed with aa. All 60 offspring show the dominant phenotype. What is the most likely genotype of the plant?',o:['AA','Aa','aa','It cannot be estimated.'],a:0,e:'Aa × aa would give about 50 % recessive offspring; with 60 offspring and none recessive, AA is most likely.',tip:'Test cross logic: any recessive offspring ⇒ parent is Aa.'},
{t:'calc',q:'For AaBb × AaBb (independent genes), what fraction of offspring shows both recessive traits?',o:['1/4','1/9','1/16','3/16'],a:2,e:'¼ (aa) × ¼ (bb) = 1/16, the "1" in 9:3:3:1.',tip:'Independent events → multiply the single probabilities.'},
{t:'multi',q:'Which statements are correct?<br>I. Two parents with the dominant phenotype can have a child with the recessive phenotype.<br>II. Two parents with the recessive phenotype can have a child with the dominant phenotype.<br>III. The genotypes AA and Aa result in the same phenotype.',o:['Only I','I and III','II and III','I, II and III'],a:1,e:'I: Aa × Aa can give aa ✓. II: aa × aa gives only aa ✗. III: dominance ✓.',tip:'Test each statement with a concrete cross.'}
]},
{id:'stoich',area:'chembio',title:'Amount of Substance and Stoichiometry',domain:'Chemistry',text:`<p>Chemists count particles in <b>moles</b> (mol). The amount of substance n is calculated from the mass m and the molar mass M: n = m ÷ M. The molar mass of a compound is the sum of the atomic masses:</p><table><tr><th>Element</th><td>H</td><td>C</td><td>O</td><td>Na</td><td>Cl</td></tr><tr><th>M (g/mol)</th><td>1</td><td>12</td><td>16</td><td>23</td><td>35.5</td></tr></table><p>A balanced reaction equation states in which <b>mole ratios</b> substances react, e.g. 2 H<sub>2</sub> + O<sub>2</sub> → 2 H<sub>2</sub>O, or CH<sub>4</sub> + 2 O<sub>2</sub> → CO<sub>2</sub> + 2 H<sub>2</sub>O. The reactant that is used up first is the <b>limiting reactant</b>; it determines how much product forms.</p><p>The concentration of a solution is c = n ÷ V (mol/L).</p>`,
qs:[
{t:'data',q:'How many moles are in 36 g of water (H₂O)?',o:['0.5 mol','2 mol','18 mol','36 mol'],a:1,e:'M = 2·1 + 16 = 18 g/mol; 36 ÷ 18 = 2 mol.',tip:'Build molar masses from the table; H₂O = 18, CO₂ = 44, CH₄ = 16 are worth memorising.'},
{t:'calc',q:'How many moles of O₂ are needed to react completely with 4 mol H₂?',o:['1 mol','2 mol','4 mol','8 mol'],a:1,e:'Ratio H₂ : O₂ = 2 : 1 ⇒ 2 mol.',tip:'Use the coefficients as a recipe.'},
{t:'calc',q:'What mass of water forms from 4 mol H₂ (enough oxygen)?',o:['36 g','72 g','144 g','8 g'],a:1,e:'4 mol H₂ → 4 mol H₂O → 4 · 18 = 72 g.',tip:'Chain: mass → moles → ratio → moles → mass.'},
{t:'calc',q:'16 g of methane (CH₄) burn completely. What mass of CO₂ is produced?',o:['16 g','22 g','44 g','88 g'],a:2,e:'16 g CH₄ = 1 mol → 1 mol CO₂ = 12 + 32 = 44 g.',tip:'Mass is not conserved per substance: always go through moles.'},
{t:'calc',q:'0.5 mol NaCl is dissolved to give 250 mL of solution. What is the concentration?',o:['0.125 mol/L','0.5 mol/L','2 mol/L','125 mol/L'],a:2,e:'c = 0.5 ÷ 0.25 = 2 mol/L.',tip:'Convert mL to L before dividing (250 mL = 0.25 L).'},
{t:'transfer',q:'2 mol H₂ and 2 mol O₂ are mixed and react completely (2 H₂ + O₂ → 2 H₂O). Which statement is correct?',o:['O₂ is limiting; 1 mol H₂ remains.','H₂ is limiting; 1 mol O₂ remains.','Both react completely.','4 mol H₂O is formed.'],a:1,e:'2 mol H₂ needs only 1 mol O₂ ⇒ H₂ is used up, 1 mol O₂ is left; 2 mol H₂O forms.',tip:'Limiting reactant: divide each amount by its coefficient; the smallest result limits.'}
]},
{id:'energy',area:'phys',title:'Work, Energy and Power',domain:'Physics / Engineering',text:`<p>When a force F moves an object a distance s in the direction of the force, <b>work</b> W = F·s is done (unit: joule, J). Lifting a mass m by the height h requires the work mgh, which is stored as <b>potential energy</b>. A moving mass has <b>kinetic energy</b> E<sub>kin</sub> = ½·m·v². Without friction, energy is conserved: potential energy can be fully converted into kinetic energy and vice versa. Use g ≈ 10 m/s².</p><p><b>Power</b> is work per time: P = W ÷ t (unit: watt, W). Machines convert only part of the input energy into useful energy; the ratio is the <b>efficiency</b> η = useful energy ÷ input energy.</p><p>A <b>lever</b> is in balance when force × lever arm is equal on both sides: F<sub>1</sub>·a<sub>1</sub> = F<sub>2</sub>·a<sub>2</sub>. A longer lever arm thus requires less force, but the force must act over a longer distance, so the work stays the same.</p>`,
qs:[
{t:'calc',q:'How much work is needed to lift a 50 kg box by 2 m?',o:['100 J','500 J','1,000 J','2,500 J'],a:2,e:'W = mgh = 50 · 10 · 2 = 1,000 J.',tip:'Weight in newtons = mass × 10.'},
{t:'calc',q:'A ball is dropped from a height of 20 m (no air resistance). How fast is it just before it hits the ground?',o:['10 m/s','14 m/s','20 m/s','200 m/s'],a:2,e:'mgh = ½mv² ⇒ v² = 2gh = 400 ⇒ v = 20 m/s. The mass cancels.',tip:'Energy conservation: mass cancels, v = √(2gh).'},
{t:'calc',q:'A motor does 1,000 J of work in 4 seconds. What is its power?',o:['0.004 W','250 W','1,004 W','4,000 W'],a:1,e:'P = 1,000 ÷ 4 = 250 W.',tip:'Power = work ÷ time, not × time.'},
{t:'calc',q:'A load of 200 N hangs 0.5 m from the pivot of a lever. What force is needed at a distance of 2 m on the other side to balance it?',o:['50 N','100 N','400 N','800 N'],a:0,e:'200 · 0.5 = F · 2 ⇒ F = 50 N.',tip:'Lever arm × 4 ⇒ force ÷ 4.'},
{t:'calc',q:'A machine receives 800 J and delivers 600 J of useful work. What is its efficiency?',o:['25 %','60 %','75 %','133 %'],a:2,e:'600 ÷ 800 = 0.75.',tip:'Efficiency can never exceed 100 %; eliminate such options immediately.'},
{t:'multi',q:'Which statements are correct?<br>I. Doubling the speed of a car quadruples its kinetic energy.<br>II. A lever reduces the work needed to lift a load.<br>III. Lifting the same mass twice as high requires twice the work.',o:['Only I','I and III','II and III','I, II and III'],a:1,e:'I: v² ✓. II: force is reduced, work is not ✗ (stated in the text). III: W ∝ h ✓.',tip:'Watch for statements that contradict an explicit sentence in the text ("the work stays the same").'}
]},
{id:'inflation',area:'econ',title:'Inflation and Real GDP',domain:'Economics',text:`<p>The <b>consumer price index</b> (CPI) measures the price level of a basket of goods relative to a base year (CPI = 100). The <b>inflation rate</b> is the percentage change of the CPI from one year to the next.</p><p>Nominal values are measured in current prices. To compare them over time, they are converted into <b>real</b> values (prices of the base year): real value = nominal value ÷ (CPI ÷ 100). The <b>real interest rate</b> is approximately the nominal interest rate minus the inflation rate.</p><p>The chart and table show data for a fictional economy (base year 2021).</p><svg viewBox="0 0 300 150" width="100%" style="max-width:340px" role="img" aria-label="Bar chart of the CPI: 2021 100, 2022 110, 2023 121, 2024 121"><g fill="currentColor" font-size="10" text-anchor="middle"><text x="60" y="145">2021</text><text x="130" y="145">2022</text><text x="200" y="145">2023</text><text x="270" y="145">2024</text></g><g fill="var(--accent)"><rect x="40" y="50" width="40" height="80"/><rect x="110" y="42" width="40" height="88"/><rect x="180" y="33.2" width="40" height="96.8"/><rect x="250" y="33.2" width="40" height="96.8"/></g><g fill="currentColor" font-size="10" text-anchor="middle"><text x="60" y="45">100</text><text x="130" y="37">110</text><text x="200" y="28">121</text><text x="270" y="28">121</text></g><line x1="30" y1="130" x2="298" y2="130" stroke="currentColor"/><text x="4" y="12" font-size="10" fill="currentColor">CPI</text></svg><table><tr><th>Year</th><td>2021</td><td>2022</td><td>2023</td><td>2024</td></tr><tr><th>Nominal GDP (bn €)</th><td>500</td><td>550</td><td>660</td><td>605</td></tr></table>`,
qs:[
{t:'data',q:'What was the inflation rate from 2022 to 2023?',o:['10 %','11 %','21 %','121 %'],a:0,e:'(121 − 110) ÷ 110 = 10 %.',tip:'Inflation is relative to the previous year, not the base year.'},
{t:'calc',q:'What was real GDP in 2023 (in 2021 prices), approximately?',o:['€545 bn','€600 bn','€660 bn','€799 bn'],a:0,e:'660 ÷ 1.21 ≈ 545.',tip:'Real = nominal ÷ price index. Divide, don\'t multiply — prices rose, so real < nominal.'},
{t:'data',q:'How did real GDP change from 2022 to 2023?',o:['It fell by about 1 %.','It stayed the same.','It rose by about 9 %.','It rose by 20 %.'],a:2,e:'Real 2022: 550 ÷ 1.10 = 500. Real 2023 ≈ 545 ⇒ +9 % (nominal +20 % minus inflation 10 %, roughly).',tip:'Quick approximation: real growth ≈ nominal growth − inflation.'},
{t:'transfer',q:'Which statement about 2024 is correct?',o:['There was inflation of about 8 %.','Real GDP fell by about 8 %.','Real GDP rose because prices were stable.','Nominal and real GDP both stayed constant.'],a:1,e:'CPI unchanged ⇒ no inflation; nominal GDP fell from 660 to 605 (−8.3 %), so real GDP fell by the same share.',tip:'With zero inflation, real and nominal change by the same percentage.'},
{t:'calc',q:'A savings account pays 7 % nominal interest while inflation is 4 %. What is the approximate real interest rate?',o:['−3 %','3 %','11 %','28 %'],a:1,e:'7 % − 4 % = 3 %.',tip:'Real rate ≈ nominal − inflation.'},
{t:'concept',q:'Inflation turns out higher than expected. Who typically loses?',o:['Borrowers with fixed nominal interest rates','Lenders who receive a fixed nominal interest rate','Nobody, because all prices rise equally','Owners of real assets such as land'],a:1,e:'Repayments lose purchasing power, so lenders receive less in real terms; borrowers gain.',tip:'Unexpected inflation redistributes from creditors to debtors.'}
]},
{id:'trade',area:'econ',title:'Comparative Advantage',domain:'Economics',text:`<p>A country has an <b>absolute advantage</b> in a good if it can produce it with fewer resources than another country. It has a <b>comparative advantage</b> if its <b>opportunity cost</b> — the amount of the other good it must give up — is lower. According to David Ricardo, both countries can gain from trade if each specialises in the good with its comparative advantage, even if one country has an absolute advantage in everything.</p><p>The table shows the hours of labour needed to produce one unit of each good:</p><table><tr><th></th><th>Cloth</th><th>Wine</th></tr><tr><th>Country A</th><td>2 h</td><td>4 h</td></tr><tr><th>Country B</th><td>6 h</td><td>8 h</td></tr></table><p>Trade is beneficial for both countries when the exchange ratio lies between their two opportunity costs.</p>`,
qs:[
{t:'data',q:'Which country has an absolute advantage in producing both goods?',o:['Country A','Country B','Neither','A in cloth only, B in wine only'],a:0,e:'A needs fewer hours for both cloth (2 < 6) and wine (4 < 8).',tip:'Absolute advantage = compare hours directly.'},
{t:'calc',q:'What is the opportunity cost of one unit of wine in country A?',o:['0.5 units of cloth','1.33 units of cloth','2 units of cloth','4 units of cloth'],a:2,e:'4 h for wine could produce 4 ÷ 2 = 2 units of cloth.',tip:'OC of X = hours for X ÷ hours for Y.'},
{t:'concept',q:'Where do the comparative advantages lie?',o:['A in both goods','A in cloth, B in wine','A in wine, B in cloth','There are no comparative advantages.'],a:1,e:'Wine costs A 2 cloth but B only 8/6 ≈ 1.33 cloth ⇒ B in wine; hence A in cloth.',tip:'Each country always has a comparative advantage in exactly one of two goods (unless costs are identical).'},
{t:'calc',q:'Which exchange ratio would benefit both countries?',o:['1 wine for 1 cloth','1 wine for 1.5 cloth','1 wine for 2.5 cloth','1 wine for 3 cloth'],a:1,e:'The ratio must lie between 1.33 and 2 cloth per wine.',tip:'Mutually beneficial terms of trade lie strictly between the two opportunity costs.'},
{t:'transfer',q:'Country B improves its cloth production to 3 hours per unit (wine unchanged). What changes?',o:['A now has comparative advantages in both goods.','B now has the comparative advantage in cloth.','Trade is no longer beneficial.','Nothing changes.'],a:1,e:'Cloth now costs B 3/8 = 0.375 wine, less than A\'s 0.5 wine ⇒ B gains the comparative advantage in cloth.',tip:'Recompute both opportunity costs after any change; don\'t reason from the old table.'},
{t:'except',q:'All of the following statements are consistent with the text EXCEPT:',o:['Specialisation can raise total output.','Opportunity cost is measured in units of the other good.','Trade is only beneficial for a country that has an absolute advantage.','A country can gain from trade even if it is less productive in every good.'],a:2,e:'The text says both countries can gain even if one has an absolute advantage in everything.',tip:'EXCEPT + "consistent with the text": look for the statement the text explicitly contradicts.'}
]},
{id:'ratios',area:'biz',title:'Financial Ratio Analysis',domain:'Business Administration',text:`<p>Financial ratios condense the income statement and the balance sheet into comparable figures. A company reports (in € thousand):</p><table><tr><th>Income statement</th><th></th><th>Balance sheet</th><th></th></tr><tr><td>Revenue</td><td>2,000</td><td>Current assets</td><td>600</td></tr><tr><td>Cost of goods sold</td><td>1,200</td><td>… of which inventory</td><td>200</td></tr><tr><td>Operating expenses</td><td>500</td><td>Total assets</td><td>2,500</td></tr><tr><td>Net profit</td><td>200</td><td>Current liabilities</td><td>400</td></tr><tr><td></td><td></td><td>Equity</td><td>1,000</td></tr><tr><td></td><td></td><td>Debt</td><td>1,500</td></tr></table><table><tr><th>Ratio</th><th>Formula</th></tr><tr><td>Gross margin</td><td>(revenue − cost of goods sold) ÷ revenue</td></tr><tr><td>Net margin</td><td>net profit ÷ revenue</td></tr><tr><td>Current ratio</td><td>current assets ÷ current liabilities</td></tr><tr><td>Quick ratio</td><td>(current assets − inventory) ÷ current liabilities</td></tr><tr><td>Return on equity (ROE)</td><td>net profit ÷ equity</td></tr><tr><td>Return on assets (ROA)</td><td>net profit ÷ total assets</td></tr><tr><td>Debt-to-equity</td><td>debt ÷ equity</td></tr></table>`,
qs:[
{t:'data',q:'What is the gross margin?',o:['10 %','25 %','40 %','60 %'],a:2,e:'(2,000 − 1,200) ÷ 2,000 = 40 %.',tip:'Locate the two numbers in the table first, then compute — don\'t mix up gross and net.'},
{t:'data',q:'What is the current ratio?',o:['0.67','1.0','1.5','2.5'],a:2,e:'600 ÷ 400 = 1.5.',tip:'"Current" = short-term items on both sides.'},
{t:'data',q:'What is the quick ratio?',o:['0.5','1.0','1.5','2.0'],a:1,e:'(600 − 200) ÷ 400 = 1.0.',tip:'Quick ratio strips out inventory, the least liquid current asset.'},
{t:'calc',q:'What is the return on equity?',o:['8 %','10 %','13 %','20 %'],a:3,e:'200 ÷ 1,000 = 20 %.',tip:'ROE uses equity only; ROA uses total assets — same numerator.'},
{t:'transfer',q:'The company pays €100 thousand of its current liabilities using cash. What happens to the current ratio?',o:['It falls to 1.25.','It stays at 1.5.','It rises to about 1.67.','It rises to 2.0.'],a:2,e:'(600 − 100) ÷ (400 − 100) = 500 ÷ 300 ≈ 1.67.',tip:'Change both numerator and denominator when a transaction touches both sides.'},
{t:'multi',q:'Which statements are correct?<br>I. The debt-to-equity ratio is 1.5.<br>II. The return on assets is 8 %.<br>III. The net margin is 20 %.',o:['Only I','I and II','II and III','I, II and III'],a:1,e:'I: 1,500 ÷ 1,000 ✓. II: 200 ÷ 2,500 = 8 % ✓. III: 200 ÷ 2,000 = 10 % ✗.',tip:'One false statement eliminates every option that contains it.'}
]},
{id:'cpm',area:'biz',title:'Project Scheduling with the Critical Path',domain:'Business / Operations',text:`<p>Projects consist of activities, some of which must wait for others to finish. The <b>critical path method</b> identifies the longest chain of dependent activities; its length is the shortest possible project duration. Activities on this path are <b>critical</b>: any delay in them delays the whole project. For all other activities, the <b>slack</b> (float) states how long they can be delayed without delaying the project.</p><table><tr><th>Activity</th><th>Duration (days)</th><th>Predecessors</th></tr><tr><td>A</td><td>3</td><td>—</td></tr><tr><td>B</td><td>2</td><td>A</td></tr><tr><td>C</td><td>4</td><td>A</td></tr><tr><td>D</td><td>3</td><td>B</td></tr><tr><td>E</td><td>2</td><td>C, D</td></tr></table><p>An activity can only start once <i>all</i> of its predecessors are finished. If a critical activity is shortened, another path may become critical.</p>`,
qs:[
{t:'data',q:'What is the minimum duration of the project?',o:['9 days','10 days','11 days','14 days'],a:1,e:'Paths: A–B–D–E = 3 + 2 + 3 + 2 = 10; A–C–E = 3 + 4 + 2 = 9. Longest = 10.',tip:'List every start-to-end path, add durations, take the longest.'},
{t:'data',q:'Which is the critical path?',o:['A–C–E','A–B–D–E','A–B–C–D–E','A–D–E'],a:1,e:'It is the longest path (10 days).',tip:'The critical path is the longest, not the shortest.'},
{t:'calc',q:'How much slack does activity C have?',o:['0 days','1 day','2 days','3 days'],a:1,e:'E must start on day 8 (after D). C can finish as late as day 8, i.e. start on day 4 instead of day 3 ⇒ 1 day.',tip:'Slack of a path activity = critical length − its path length (when it is on one path only): 10 − 9 = 1.'},
{t:'transfer',q:'Activity C is delayed by 3 days. What is the new project duration?',o:['10 days','11 days','12 days','13 days'],a:2,e:'A–C–E becomes 12 days, which is now the longest path.',tip:'A delay larger than the slack extends the project by (delay − slack): 3 − 1 = 2 days.'},
{t:'transfer',q:'Activity D is shortened by 2 days. What is the new project duration?',o:['7 days','8 days','9 days','10 days'],a:2,e:'A–B–D–E becomes 8, but A–C–E is still 9 ⇒ 9 days.',tip:'Shortening the critical path only helps until another path becomes the longest.'},
{t:'concept',q:'What is true for every activity on the critical path?',o:['It has the longest individual duration.','It has zero slack.','It can be delayed by one day without consequences.','It has no predecessors.'],a:1,e:'By definition, critical activities cannot be delayed without delaying the project.',tip:'Critical = zero float.'}
]},
{id:'sql',area:'cs',title:'Relational Databases',domain:'Computer Science',text:`<p>A relational database stores data in tables. A <b>primary key</b> uniquely identifies each row; a <b>foreign key</b> refers to the primary key of another table. SQL queries select data: <code>WHERE</code> filters rows, an <b>INNER JOIN</b> returns only rows with matching keys in both tables, a <b>LEFT JOIN</b> additionally keeps rows of the left table without a match (with empty values), and <code>GROUP BY … COUNT(*)</code> counts rows per group.</p><table><tr><th colspan="3">Students</th></tr><tr><th>id</th><th>name</th><th>city</th></tr><tr><td>1</td><td>Anna</td><td>Berlin</td></tr><tr><td>2</td><td>Ben</td><td>Munich</td></tr><tr><td>3</td><td>Chen</td><td>Berlin</td></tr><tr><td>4</td><td>Dara</td><td>Hamburg</td></tr></table><table><tr><th colspan="2">Enrolments</th></tr><tr><th>student_id</th><th>course</th></tr><tr><td>1</td><td>Math</td></tr><tr><td>1</td><td>Physics</td></tr><tr><td>2</td><td>Math</td></tr><tr><td>3</td><td>History</td></tr><tr><td>3</td><td>Math</td></tr></table>`,
qs:[
{t:'data',q:'How many rows does <code>SELECT name FROM Students WHERE city = \'Berlin\'</code> return?',o:['1','2','3','4'],a:1,e:'Anna and Chen.',tip:'Filter first, count second.'},
{t:'data',q:'How many rows result from <code>Students INNER JOIN Enrolments ON Students.id = Enrolments.student_id</code>?',o:['4','5','6','9'],a:1,e:'One row per enrolment with a matching student: 5.',tip:'An inner join produces one row per matching pair — here, per enrolment.'},
{t:'data',q:'How many rows result from the same join written as a LEFT JOIN (Students on the left)?',o:['4','5','6','20'],a:2,e:'The 5 matches plus Dara without enrolments = 6.',tip:'LEFT JOIN = inner join rows + unmatched left rows.'},
{t:'data',q:'<code>SELECT course, COUNT(*) FROM Enrolments GROUP BY course</code> — what count is shown for Math?',o:['1','2','3','5'],a:2,e:'Students 1, 2 and 3 take Math.',tip:'Group, then count rows inside each group.'},
{t:'concept',q:'Which would be a suitable primary key for the Enrolments table?',o:['student_id alone','course alone','The combination (student_id, course)','There is no suitable key.'],a:2,e:'student_id and course repeat individually; each pair is unique.',tip:'Test a key candidate: does any value repeat?'},
{t:'multi',q:'Which statements are correct?<br>I. Dara appears in the result of the inner join.<br>II. Enrolments.student_id is a foreign key.<br>III. Deleting Anna from Students without handling her enrolments would break referential integrity.',o:['Only II','I and II','II and III','I, II and III'],a:2,e:'I ✗ (no enrolment). II ✓. III ✓ (enrolments would point to a missing student).',tip:'Foreign keys must always point to an existing row.'}
]},
{id:'graphs',area:'cs',title:'Shortest Paths in Networks',domain:'Computer Science / Engineering',text:`<p>Road or computer networks can be modelled as <b>graphs</b>: nodes connected by edges with weights (e.g. travel times). <b>Dijkstra's algorithm</b> finds the shortest paths from a start node: it repeatedly takes the unvisited node with the smallest known distance, marks it as final and updates the distances of its neighbours. The algorithm requires all edge weights to be <b>non-negative</b>. If all edges count equally, a breadth-first search finds the path with the fewest edges.</p><p>The figure shows an undirected network with travel times in minutes.</p><svg viewBox="0 0 360 180" width="100%" style="max-width:380px" role="img" aria-label="Network: S–A 4, S–B 1, B–A 2, A–C 1, B–C 5, C–T 3, A–T 6"><g stroke="currentColor" stroke-width="1.6"><line x1="30" y1="90" x2="130" y2="30"/><line x1="30" y1="90" x2="130" y2="150"/><line x1="130" y1="150" x2="130" y2="30"/><line x1="130" y1="30" x2="230" y2="90"/><line x1="130" y1="150" x2="230" y2="90"/><line x1="230" y1="90" x2="330" y2="90"/><path d="M130,30 Q250,-5 330,90" fill="none"/></g><g font-size="12" fill="currentColor" font-weight="700"><text x="70" y="52">4</text><text x="70" y="136">1</text><text x="136" y="94">2</text><text x="186" y="52">1</text><text x="186" y="136">5</text><text x="276" y="84">3</text><text x="262" y="22">6</text></g><g fill="var(--accent)"><circle cx="30" cy="90" r="13"/><circle cx="130" cy="30" r="13"/><circle cx="130" cy="150" r="13"/><circle cx="230" cy="90" r="13"/><circle cx="330" cy="90" r="13"/></g><g font-size="12" fill="var(--accent-ink)" text-anchor="middle" font-weight="700"><text x="30" y="94">S</text><text x="130" y="34">A</text><text x="130" y="154">B</text><text x="230" y="94">C</text><text x="330" y="94">T</text></g></svg>`,
qs:[
{t:'data',q:'What is the shortest travel time from S to A?',o:['2 min','3 min','4 min','5 min'],a:1,e:'Via B: 1 + 2 = 3 < 4 (direct).',tip:'The direct edge is not always the shortest route — check two-step detours.'},
{t:'data',q:'What is the shortest travel time from S to T?',o:['7 min','8 min','9 min','10 min'],a:0,e:'S–B–A–C–T = 1 + 2 + 1 + 3 = 7.',tip:'Build distances outward: S→B 1, S→A 3, S→C 4, S→T 7.'},
{t:'data',q:'Which route is the shortest path from S to T?',o:['S–A–T','S–B–C–T','S–B–A–C–T','S–A–C–T'],a:2,e:'7 min; S–A–T = 10, S–B–C–T = 9, S–A–C–T = 8.',tip:'Compute each option\'s total — faster than running the whole algorithm.'},
{t:'data',q:'Ignoring the weights, which path from S to T uses the fewest edges?',o:['S–A–T','S–B–C–T','S–B–A–C–T','S–A–C–T'],a:0,e:'Two edges.',tip:'Fewest edges ≠ shortest time.'},
{t:'transfer',q:'The road between B and A is closed. What is the new shortest time from S to T?',o:['7 min','8 min','9 min','10 min'],a:1,e:'S→A = 4, S→C = min(4 + 1, 1 + 5) = 5, S→T = min(5 + 3, 4 + 6) = 8.',tip:'After a change, recompute only the distances that depended on the removed edge.'},
{t:'concept',q:'Why may Dijkstra\'s algorithm fail when a network contains an edge with weight −2?',o:['Because the graph becomes directed','Because a node marked as final could later be reached more cheaply','Because the algorithm cannot handle more than 5 nodes','Because negative weights make all paths equally long'],a:1,e:'The algorithm assumes distances only grow along a path; negative edges break that assumption.',tip:'Link each answer back to a stated requirement in the text ("non-negative").'}
]},
{id:'voting',area:'soc',title:'Voting Systems',domain:'Political Science',text:`<p>How votes are counted can decide who wins. Consider 100 voters ranking three candidates:</p><table><tr><th>Voters</th><th>1st</th><th>2nd</th><th>3rd</th></tr><tr><td>40</td><td>X</td><td>Y</td><td>Z</td></tr><tr><td>35</td><td>Z</td><td>Y</td><td>X</td></tr><tr><td>25</td><td>Y</td><td>Z</td><td>X</td></tr></table><ul><li><b>Plurality:</b> the candidate with the most first preferences wins.</li><li><b>Runoff:</b> the two candidates with the most first preferences meet in a second round; each voter supports whichever of the two they rank higher.</li><li><b>Borda count:</b> 2 points for each first place, 1 for each second, 0 for each third; the most points wins.</li><li><b>Condorcet winner:</b> a candidate who beats every other candidate in a head-to-head comparison (if one exists).</li></ul>`,
qs:[
{t:'data',q:'Who wins under the plurality rule?',o:['X','Y','Z','Tie between X and Z'],a:0,e:'X 40, Z 35, Y 25.',tip:'Only count the 1st column.'},
{t:'data',q:'Who wins the runoff?',o:['X','Y','Z','Tie'],a:2,e:'X vs Z: the 25 Y-voters prefer Z ⇒ Z 60 : X 40.',tip:'Eliminated candidates\' voters move to whichever finalist they rank higher.'},
{t:'calc',q:'How many Borda points does Y receive?',o:['65','95','125','140'],a:2,e:'40·1 + 35·1 + 25·2 = 125 (X: 80, Z: 95).',tip:'Multiply each group size by the points for that candidate\'s position, then add.'},
{t:'data',q:'Is there a Condorcet winner?',o:['Yes, X','Yes, Y','Yes, Z','No'],a:1,e:'Y beats X 60 : 40 and Z 65 : 35.',tip:'For each pair, count who ranks whom higher — the third candidate is irrelevant.'},
{t:'concept',q:'What does the example illustrate?',o:['All voting rules produce the same result.','The same preferences can yield different winners under different rules.','The plurality winner is always the Condorcet winner.','Borda counts always favour the plurality winner.'],a:1,e:'Plurality: X, runoff: Z, Borda/Condorcet: Y.',tip:'"What does the example illustrate?" = state the general lesson, not a detail.'},
{t:'multi',q:'Which statements are correct?<br>I. X is supported by an absolute majority of first preferences.<br>II. Z beats X in a head-to-head comparison.<br>III. X loses every head-to-head comparison.',o:['Only II','I and II','II and III','I, II and III'],a:2,e:'I: 40 % is not > 50 % ✗. II: 60 : 40 ✓. III: X loses to Y and Z (40 : 60 each) ✓.',tip:'"Absolute majority" means more than half — a common trap word.'}
]},
{id:'logic',area:'soc',title:'Analysing Arguments',domain:'Philosophy / Humanities',text:`<p>An argument consists of <b>premises</b> and a <b>conclusion</b>. It is <b>valid</b> if the conclusion necessarily follows from the premises, regardless of whether the premises are true. It is <b>sound</b> if it is valid <i>and</i> all premises are true.</p><table><tr><th>Form</th><th>Pattern</th><th>Valid?</th></tr><tr><td>Modus ponens</td><td>If P, then Q. P. So Q.</td><td>yes</td></tr><tr><td>Modus tollens</td><td>If P, then Q. Not Q. So not P.</td><td>yes</td></tr><tr><td>Affirming the consequent</td><td>If P, then Q. Q. So P.</td><td>no</td></tr><tr><td>Denying the antecedent</td><td>If P, then Q. Not P. So not Q.</td><td>no</td></tr></table><p>Common informal <b>fallacies</b>: <i>ad hominem</i> (attacking the person instead of the claim), <i>straw man</i> (refuting a distorted version of a position), <i>false dilemma</i> (presenting only two options when more exist) and <i>post hoc</i> (concluding that A caused B because B followed A).</p>`,
qs:[
{t:'data',q:'"If it rains, the street is wet. The street is wet. Therefore, it rained." Which form is this?',o:['Modus ponens','Modus tollens','Affirming the consequent','Denying the antecedent'],a:2,e:'Q is affirmed and P inferred — invalid (the street could be wet for other reasons).',tip:'Map the sentence to P and Q, then compare with the table rows.'},
{t:'data',q:'"If the alarm works, it sounds during a fire. It did not sound. So the alarm does not work." — assuming there was a fire, which form is used?',o:['Modus ponens','Modus tollens','Affirming the consequent','Denying the antecedent'],a:1,e:'Not Q ⇒ not P: valid.',tip:'"Not Q, so not P" is the valid one; "not P, so not Q" is the invalid one.'},
{t:'concept',q:'"All birds can fly. Penguins are birds. So penguins can fly." How is this argument best described?',o:['Valid and sound','Valid but not sound','Invalid but sound','Invalid and not sound'],a:1,e:'The conclusion follows logically, but the first premise is false.',tip:'Validity is about structure; soundness adds true premises.'},
{t:'concept',q:'"We can ignore her study on air pollution — she drives a car herself." Which fallacy is this?',o:['Straw man','Ad hominem','False dilemma','Post hoc'],a:1,e:'The person is attacked, not the evidence.',tip:'Ask: does the reply address the claim or the person?'},
{t:'concept',q:'"Since the new mayor took office, the crime rate has risen. The mayor is responsible for the rise." Which fallacy is this?',o:['Ad hominem','False dilemma','Post hoc','Straw man'],a:2,e:'A temporal sequence is taken as proof of causation.',tip:'"After" ≠ "because of" — same idea as correlation vs causation.'},
{t:'except',q:'Each of the following arguments is valid EXCEPT:',o:['If P then Q; P; so Q.','If P then Q; not Q; so not P.','If P then Q; not P; so not Q.','All A are B; x is an A; so x is a B.'],a:2,e:'Denying the antecedent is invalid.',tip:'Test with a quick counterexample: "If it\'s a dog, it\'s an animal. It isn\'t a dog. So it isn\'t an animal." — clearly wrong for a cat.'}
]},
{id:'demog',area:'soc',title:'Population Structure',domain:'Social Sciences / Geography',text:`<p>Demographers describe populations with a few key figures. The <b>dependency ratio</b> relates the population of typically non-working age to the working-age population: (people aged 0–14 + people aged 65+) ÷ people aged 15–64 × 100. The <b>crude birth rate</b> is the number of births per 1,000 inhabitants per year (the crude death rate analogously). A population's growth consists of natural increase (births − deaths) plus net migration.</p><p>A <b>population pyramid</b> shows the age structure: a wide base indicates many young people and typically a growing population; a narrow base and wide top indicate an ageing population.</p><table><tr><th colspan="2">Country R (one year)</th></tr><tr><td>Population aged 0–14</td><td>30 million</td></tr><tr><td>Population aged 15–64</td><td>60 million</td></tr><tr><td>Population aged 65+</td><td>10 million</td></tr><tr><td>Births</td><td>2.0 million</td></tr><tr><td>Deaths</td><td>0.8 million</td></tr><tr><td>Net migration</td><td>+0.2 million</td></tr></table>`,
qs:[
{t:'data',q:'What is the dependency ratio of country R?',o:['40','50','about 67','150'],a:2,e:'(30 + 10) ÷ 60 × 100 ≈ 66.7.',tip:'Numerator: the young and the old; denominator: working age only.'},
{t:'calc',q:'What is the crude birth rate?',o:['2 per 1,000','20 per 1,000','33 per 1,000','200 per 1,000'],a:1,e:'Total population 100 million; 2.0 ÷ 100 × 1,000 = 20.',tip:'"Per 1,000" = per mille; divide by the total population, not the working-age group.'},
{t:'calc',q:'By what percentage does the population grow in this year?',o:['1.2 %','1.4 %','2.0 %','2.2 %'],a:1,e:'(2.0 − 0.8 + 0.2) ÷ 100 = 1.4 %.',tip:'Don\'t forget migration — the text defines growth to include it.'},
{t:'transfer',q:'If this growth rate stayed constant, after roughly how many years would the population double? (Rule of 70)',o:['about 14 years','about 35 years','about 50 years','about 70 years'],a:2,e:'70 ÷ 1.4 = 50.',tip:'Rule of 70 transfers across subjects: economics, biology, demography.'},
{t:'concept',q:'What does a population pyramid with a very wide base most likely indicate?',o:['An ageing, shrinking population','A young, growing population','A population with high life expectancy only','Strong emigration of young adults'],a:1,e:'Many children ⇒ high birth rates ⇒ growth.',tip:'Read shape → age structure → trend.'},
{t:'transfer',q:'The number of people aged 65+ doubles while the other groups stay the same. What is the new dependency ratio?',o:['about 67','about 75','about 83','100'],a:2,e:'(30 + 20) ÷ 60 × 100 ≈ 83.3.',tip:'Only the changed number moves; keep the denominator fixed.'}
]}
];
