/* Subject Module texts and questions — the third batch: economics, business, humanities and biology.
   Each entry: { id, area, title, domain, text (HTML), qs: [{ t, q, o[4], a, e, tip }] }.
   `a` is the index of the correct option; options are shuffled at runtime.
   See CONTRIBUTING.md for how to add one. */
const MORE2=[
{id:'monetary',area:'econ',title:'Central Banks and Interest Rates',domain:'Economics',text:`<p>A central bank steers the economy mainly through its <b>policy interest rate</b>. When it <b>raises</b> the rate, borrowing becomes more expensive for banks, firms and households; credit, investment and consumption tend to fall, which dampens demand and, with a delay of often one to two years, inflation. Higher rates also make a currency more attractive to foreign investors, so it tends to <b>appreciate</b>. <b>Lowering</b> the rate has the opposite effects and is used to support a weak economy.</p><p>Bond prices move <b>inversely</b> to interest rates: an existing bond with a fixed coupon becomes less attractive when new bonds pay more, so its price falls. A bond paying €50 per year forever (a perpetuity) is worth approximately coupon ÷ market interest rate.</p><p>The <b>quantity equation</b> links money and prices: M · V = P · Y (money supply × velocity of money = price level × real output). If V and Y are constant, prices rise in proportion to the money supply.</p>`,
qs:[
{t:'concept',q:'Inflation is well above the central bank\'s target. What is the typical policy response?',o:['Lower the policy rate','Raise the policy rate','Keep the rate and print more money','Abolish the currency peg'],a:1,e:'Higher rates dampen demand and, with a lag, inflation.',tip:'Rates up = brakes on; rates down = accelerator.'},
{t:'transfer',q:'The central bank raises its policy rate. Which combination of effects is most likely?',o:['More investment, weaker currency','Less investment, stronger currency','More consumption, stronger currency','Less investment, weaker currency'],a:1,e:'Borrowing becomes costlier (investment ↓) and the currency attracts capital (appreciates).',tip:'Chain the text\'s cause–effect sentences one link at a time.'},
{t:'calc',q:'A perpetual bond pays €50 per year. What is it worth when market interest rates are 5 %?',o:['€250','€500','€1,000','€2,500'],a:2,e:'50 ÷ 0.05 = 1,000.',tip:'Perpetuity value = payment ÷ rate.'},
{t:'calc',q:'Market rates for the same bond rise from 5 % to 10 %. What happens to its price?',o:['It doubles to €2,000.','It stays at €1,000.','It halves to €500.','It falls to €950.'],a:2,e:'50 ÷ 0.10 = 500: price and rate move inversely.',tip:'Rate doubles ⇒ perpetuity price halves.'},
{t:'calc',q:'With velocity and real output constant, the money supply grows by 8 %. By roughly how much does the price level change?',o:['0 %','4 %','8 %','16 %'],a:2,e:'M·V = P·Y with V, Y fixed ⇒ P ∝ M.',tip:'Hold the fixed terms constant and read off the proportionality.'},
{t:'except',q:'All of the following statements are consistent with the text EXCEPT:',o:['Monetary policy affects inflation with a delay.','A rate cut can support a weak economy.','Bond prices rise when interest rates rise.','Higher rates can strengthen a currency.'],a:2,e:'The text states bond prices move inversely to rates.',tip:'Look for the option that flips a direction stated in the text.'}
]},
{id:'marketing',area:'biz',title:'Customer Metrics in Marketing',domain:'Business Administration',text:`<p>Firms track a few metrics to judge whether customers are worth acquiring. <b>Market share</b> is a firm's sales divided by total market sales. The <b>conversion rate</b> is the share of visitors (or leads) that make a purchase. <b>Customer acquisition cost</b> (CAC) is marketing spending divided by the number of new customers won.</p><p>The <b>customer lifetime value</b> (CLV) estimates the profit a customer brings over the whole relationship. A simple version is:</p><p style="text-align:center">CLV = average yearly profit per customer × average customer lifetime in years</p><p>The average lifetime can be estimated as 1 ÷ churn rate, where the <b>churn rate</b> is the share of customers lost per year. A business model is usually considered healthy if CLV is at least three times CAC.</p><table><tr><th>Online shop, last year</th><td></td></tr><tr><td>Website visitors</td><td>200,000</td></tr><tr><td>New customers</td><td>4,000</td></tr><tr><td>Marketing spend</td><td>€120,000</td></tr><tr><td>Yearly profit per customer</td><td>€25</td></tr><tr><td>Churn rate</td><td>20 % per year</td></tr><tr><td>Shop sales / total market sales</td><td>€6 m / €40 m</td></tr></table>`,
qs:[
{t:'data',q:'What is the conversion rate of the shop?',o:['0.2 %','2 %','4 %','20 %'],a:1,e:'4,000 ÷ 200,000 = 2 %.',tip:'Rate = the smaller group ÷ the group it came from.'},
{t:'data',q:'What is the customer acquisition cost?',o:['€3','€25','€30','€48'],a:2,e:'120,000 ÷ 4,000 = €30.',tip:'Spend ÷ new customers — not ÷ visitors.'},
{t:'calc',q:'What is the average customer lifetime and the CLV?',o:['2 years; €50','5 years; €125','5 years; €25','20 years; €500'],a:1,e:'Lifetime = 1 ÷ 0.2 = 5 years; CLV = 25 × 5 = €125.',tip:'Churn 20 % ⇒ 1/0.2 = 5 years. Memorise 1/churn.'},
{t:'data',q:'What is the shop\'s market share?',o:['6 %','15 %','34 %','40 %'],a:1,e:'6 ÷ 40 = 15 %.',tip:'Keep units consistent (both in € million).'},
{t:'transfer',q:'Is the shop\'s business model healthy by the 3× rule, and what would change the answer?',o:['Yes; CLV is more than 4× CAC. Doubling churn to 40 % would drop the ratio to about 2×.','No; CLV is below CAC.','Yes; but only because the market share is high.','No; the conversion rate is below 5 %.'],a:0,e:'125 ÷ 30 ≈ 4.2 ≥ 3. With 40 % churn: lifetime 2.5 years, CLV 62.5, ratio ≈ 2.1.',tip:'Transfer questions often test one change — recompute only the affected chain.'},
{t:'multi',q:'Which statements are correct?<br>I. Halving the churn rate doubles the CLV.<br>II. Doubling marketing spend with the same number of new customers doubles the CAC.<br>III. A higher conversion rate always lowers market share.',o:['Only I','I and II','II and III','I, II and III'],a:1,e:'I: lifetime 1/0.1 = 10 years ⇒ CLV doubles ✓. II ✓. III: no such relation ✗.',tip:'"Always" in a statement is a red flag — look for the counterexample.'}
]},
{id:'sources',area:'soc',title:'Working with Historical Sources',domain:'History / Humanities',text:`<p>Historians distinguish <b>primary sources</b> — material created at the time under study, such as letters, diaries, laws, photographs or newspaper reports — from <b>secondary sources</b>, which interpret the past afterwards, such as textbooks and scholarly articles.</p><p><b>Source criticism</b> asks: Who created the source, when, for whom and why? A source written close in time to the event by an eyewitness is often more <i>direct</i>, but it may also be <i>partial</i> — shaped by the author's interests, the intended audience or censorship. Official documents show what a government wanted to be recorded, not necessarily what happened. Private diaries were usually not meant for publication and may reveal views their authors hid in public.</p><p><b>Corroboration</b> means checking a claim against independent sources. Agreement between sources that depend on each other (for example, two newspapers copying the same agency report) adds little evidence. Historians also note what a source leaves out (<b>silences</b>), since omissions can be as informative as statements.</p>`,
qs:[
{t:'concept',q:'Which of the following is a primary source for a study of a 1920s strike?',o:['A 2015 book about the strike','A strike leaflet printed in 1923','A documentary film made in 1990','An encyclopedia entry on labour history'],a:1,e:'Created at the time under study.',tip:'Primary = made during the period studied, whatever its form.'},
{t:'concept',q:'A government press release from 1923 claims the strike ended "peacefully". How should a historian treat this?',o:['As proof that the strike ended peacefully','As evidence of how the government wanted the event to be seen, to be checked against other sources','As a secondary source','As irrelevant because it is official'],a:1,e:'Official documents show what the authorities wanted recorded.',tip:'Ask "who, for whom, why?" before "is it true?".'},
{t:'transfer',q:'Two newspapers report the same casualty figure, both citing the same news agency. What does this agreement add?',o:['Strong independent confirmation','Little additional evidence, because the sources are not independent','Proof that the agency was wrong','Nothing, because newspapers are secondary sources'],a:1,e:'Corroboration requires independent sources.',tip:'Count independent origins, not the number of copies.'},
{t:'concept',q:'Why might a private diary reveal things an official speech does not?',o:['Diaries are always more accurate.','Diaries were usually not meant for publication, so authors may record views they hid in public.','Diaries are secondary sources.','Speeches are never primary sources.'],a:1,e:'Stated in the text.',tip:'Eliminate absolute words ("always", "never") unless the text uses them.'},
{t:'concept',q:'A company\'s annual reports from the 1930s never mention its use of forced labour, which is documented elsewhere. What does this illustrate?',o:['Corroboration','A secondary source','A meaningful silence','Eyewitness directness'],a:2,e:'Omissions can be informative.',tip:'Match the scenario to the defined term, word for word.'},
{t:'except',q:'All of the following are questions of source criticism EXCEPT:',o:['Who created the source?','For which audience was it written?','Why was it produced?','How many pages does the source have?'],a:3,e:'Length is not among the text\'s criteria.',tip:'EXCEPT: pick the option that does not belong to the list the text defines.'}
]},
{id:'ecology',area:'chembio',title:'Population Growth in Ecology',domain:'Biology',text:`<p>With unlimited resources, a population grows <b>exponentially</b>. In reality, space and food are limited, and growth slows as the population approaches the <b>carrying capacity</b> K — the largest population the environment can sustain. This is described by <b>logistic growth</b>:</p><p style="text-align:center">growth per year = r · N · (1 − N ÷ K)</p><p>where N is the current population and r the intrinsic growth rate. Growth is fastest when N = K ÷ 2 and approaches zero as N approaches K.</p><svg viewBox="0 0 320 150" width="100%" style="max-width:360px" role="img" aria-label="S-shaped logistic curve rising toward K, steepest at K/2"><line x1="30" y1="130" x2="310" y2="130" stroke="currentColor"/><line x1="30" y1="130" x2="30" y2="10" stroke="currentColor"/><line x1="30" y1="25" x2="310" y2="25" stroke="currentColor" stroke-dasharray="4 4" opacity=".6"/><line x1="30" y1="77.5" x2="310" y2="77.5" stroke="currentColor" stroke-dasharray="2 4" opacity=".4"/><path d="M30,126 C110,124 130,80 160,77.5 C190,75 210,30 310,27" fill="none" stroke="var(--accent)" stroke-width="3"/><g font-size="11" fill="currentColor"><text x="4" y="29">K</text><text x="0" y="81">K/2</text><text x="250" y="145">time</text><text x="36" y="18">N</text></g></svg><p>In <b>predator–prey</b> systems (e.g. lynx and hares), the populations oscillate: many prey allow predators to multiply; more predators reduce the prey; fewer prey cause predators to decline, after which prey recover. The predator peaks typically <b>lag behind</b> the prey peaks.</p>`,
qs:[
{t:'data',q:'At which population size is the growth rate highest?',o:['Close to zero','At K ÷ 2','At K','Above K'],a:1,e:'The curve is steepest at K/2.',tip:'Steepest point of an S-curve = fastest growth.'},
{t:'calc',q:'r = 0.5 per year, K = 1,000, N = 500. What is the growth per year?',o:['62.5','125','250','500'],a:1,e:'0.5 · 500 · (1 − 0.5) = 125.',tip:'Plug in stepwise: r·N first, then the brake factor.'},
{t:'calc',q:'Same values, but N = 900. What is the growth per year?',o:['45','90','225','450'],a:0,e:'0.5 · 900 · 0.1 = 45.',tip:'Near K the brake factor (1 − N/K) is small.'},
{t:'transfer',q:'A population is at N = 1,200 with K = 1,000. What does the model predict?',o:['Faster growth','No change','A decrease','Exponential growth'],a:2,e:'1 − 1.2 = −0.2 ⇒ negative growth.',tip:'Check the sign of each factor.'},
{t:'concept',q:'In a predator–prey cycle, what typically happens right after the prey population peaks?',o:['Predators decline immediately.','Predators continue to increase for a while.','Both populations stay constant.','Prey keep increasing indefinitely.'],a:1,e:'Predator peaks lag behind prey peaks.',tip:'"Lag" = the follower peaks after the leader.'},
{t:'multi',q:'Which statements are correct?<br>I. Logistic growth starts almost exponentially.<br>II. The carrying capacity is the highest growth rate.<br>III. Without resource limits, growth would be exponential.',o:['Only I','I and III','II and III','I, II and III'],a:1,e:'I ✓ (N ≪ K ⇒ brake ≈ 1). II ✗ (K is a population size). III ✓.',tip:'Watch for statements that mix up a quantity with a rate.'}
]}
];
