const PASSAGES=[
{id:'stats',title:'Describing Data: Centre and Spread',domain:'Statistics',text:`<p>Descriptive statistics summarise a data set with a few numbers. The <b>arithmetic mean</b> is the sum of all values divided by their number. The <b>median</b> is the middle value once the data are sorted (for an even number of values, the mean of the two middle values). The <b>mode</b> is the most frequent value. The <b>range</b> is the difference between the largest and smallest value.</p><p>The <b>standard deviation</b> (SD) measures how far values typically lie from the mean; the <b>variance</b> is the square of the SD. The mean and the SD react strongly to extreme values (outliers), whereas the median is considered <i>robust</i>.</p><p>A researcher recorded the commuting times (in minutes) of seven employees:</p><table><tr><th>Employee</th><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td></tr><tr><th>Minutes</th><td>12</td><td>15</td><td>15</td><td>18</td><td>20</td><td>22</td><td>45</td></tr></table>`,
qs:[
{q:'What is the median commuting time?',o:['15 minutes','18 minutes','20 minutes','21 minutes'],a:1,e:'Sorted values: 12, 15, 15, <b>18</b>, 20, 22, 45 — the 4th of 7 values is 18.'},
{q:'What is the mean commuting time?',o:['18 minutes','19 minutes','21 minutes','23 minutes'],a:2,e:'Sum = 147; 147 ÷ 7 = 21.'},
{q:'The value 45 is corrected to 25. Which statement is correct?',o:['Mean and median both decrease.','The mean decreases; the median stays the same.','The median decreases; the mean stays the same.','Neither the mean nor the median changes.'],a:1,e:'The largest value changes but stays the largest, so the middle value (18) is unchanged. The sum drops by 20, so the mean falls (to about 18.1).'},
{q:'What is the mode of the data?',o:['12','15','18','There is no mode.'],a:1,e:'15 occurs twice; every other value once.'},
{q:'Every employee\'s commute becomes 5 minutes longer. What happens?',o:['Mean +5, SD +5','Mean +5, SD unchanged','Mean unchanged, SD +5','Mean ×5, SD ×5'],a:1,e:'Adding a constant shifts all values equally: the centre moves, the spread does not.'},
{q:'All values are doubled (e.g. converted to a longer route). How does the variance change?',o:['It stays the same.','It doubles.','It quadruples.','It halves.'],a:2,e:'Multiplying by 2 doubles the SD; variance = SD², so it becomes 2² = 4 times as large.'}
]},
{id:'bayes',title:'Diagnostic Tests and Conditional Probability',domain:'Probability / Medicine',text:`<p>The quality of a medical test is described by two figures. <b>Sensitivity</b> is the probability that the test is positive when a person has the disease. <b>Specificity</b> is the probability that the test is negative when a person is healthy. The share of the population that has the disease is called <b>prevalence</b>.</p><p>What matters to a patient with a positive result is the <b>positive predictive value</b> (PPV): the probability of actually being ill given a positive test. It can be found by imagining a large group of people and counting:</p><p style="text-align:center">PPV = true positives ÷ (true positives + false positives)</p><p>Consider a disease with a prevalence of 1 %. A screening test has a sensitivity of 90 % and a specificity of 91 %. Imagine 10,000 people are screened.</p>`,
qs:[
{q:'How many of the 10,000 people are ill and test positive (true positives)?',o:['9','90','100','900'],a:1,e:'1 % of 10,000 = 100 ill; 90 % of 100 = 90.'},
{q:'How many healthy people test positive (false positives)?',o:['about 90','about 891','about 900','about 9,009'],a:1,e:'9,900 healthy; specificity 91 % ⇒ 9 % false positives; 9 % of 9,900 = 891.'},
{q:'Approximately how large is the positive predictive value?',o:['about 9 %','about 50 %','about 90 %','about 91 %'],a:0,e:'90 ÷ (90 + 891) = 90 ÷ 981 ≈ 9 %.'},
{q:'The same test is used in a clinic where 20 % of patients have the disease. How does the PPV change?',o:['It stays the same, because sensitivity and specificity are unchanged.','It increases.','It decreases.','It becomes exactly 90 %.'],a:1,e:'With higher prevalence, true positives rise and false positives fall relative to each other, so the PPV increases.'},
{q:'What is the probability that an ill person receives a negative result?',o:['1 %','9 %','10 %','91 %'],a:2,e:'1 − sensitivity = 1 − 0.90 = 10 % (false-negative rate).'},
{q:'A healthy person is tested twice; the results are independent. What is the probability that both tests are (falsely) positive?',o:['about 0.8 %','about 9 %','about 18 %','about 81 %'],a:0,e:'0.09 × 0.09 = 0.0081 ≈ 0.8 %.'}
]},
{id:'growth',title:'Exponential Growth and Decay',domain:'Mathematics / Biology',text:`<p>A quantity grows <b>exponentially</b> when it increases by the same factor in equal time intervals. For a bacterial culture with initial count N<sub>0</sub> and doubling time T:</p><p style="text-align:center">N(t) = N<sub>0</sub> · 2<sup>t/T</sup></p><p>Decay works the same way with a <b>half-life</b> T<sub>½</sub>: after each half-life only half of the quantity remains.</p><p>For growth at a constant rate of p percent per period, the doubling time can be estimated with the <b>rule of 70</b>: doubling time ≈ 70 ÷ p periods.</p><p>Logarithms are the inverse of exponentiation: log<sub>b</sub>(x) = y means b<sup>y</sup> = x. For example, log<sub>2</sub>(8) = 3. If the vertical axis of a graph is logarithmic, exponential growth appears as a straight line.</p>`,
qs:[
{q:'A culture starts with 500 bacteria and doubles every 20 minutes. How many bacteria are there after one hour?',o:['1,500','2,000','3,000','4,000'],a:3,e:'60 min = 3 doublings: 500 · 2³ = 4,000.'},
{q:'An economy grows by 7 % per year. After roughly how many years has it doubled?',o:['about 5 years','about 7 years','about 10 years','about 14 years'],a:2,e:'Rule of 70: 70 ÷ 7 = 10.'},
{q:'A culture doubles every 3 hours. After about how long has it grown roughly 1,000-fold?',o:['about 10 hours','about 30 hours','about 300 hours','about 3,000 hours'],a:1,e:'2¹⁰ = 1,024 ≈ 1,000 ⇒ 10 doublings × 3 h = 30 h.'},
{q:'What is log₂(32) + log₁₀(100)?',o:['5','7','10','132'],a:1,e:'log₂(32) = 5 and log₁₀(100) = 2; 5 + 2 = 7.'},
{q:'A sample contains 80 g of a substance with a half-life of 5 years. How much remains after 15 years?',o:['5 g','10 g','20 g','26.7 g'],a:1,e:'15 years = 3 half-lives: 80 → 40 → 20 → 10 g.'},
{q:'A process is plotted with a logarithmic vertical axis and a linear time axis. The curve is a rising straight line. What does this indicate?',o:['Linear growth','Exponential growth','Growth that slows down over time','No growth'],a:1,e:'On a log scale, a constant growth factor per time step becomes a constant increase ⇒ straight line.'}
]},
{id:'elasticity',title:'Price Elasticity of Demand',domain:'Economics',text:`<p>The <b>price elasticity of demand</b> (E) measures how strongly the quantity demanded reacts to a change in price:</p><p style="text-align:center">E = (percentage change in quantity) ÷ (percentage change in price)</p><p>Because demand usually falls when prices rise, E is normally negative; economists often compare its absolute value. If |E| &gt; 1, demand is <b>elastic</b>: quantity reacts more than proportionally, so a price increase <i>reduces</i> revenue (price × quantity). If |E| &lt; 1, demand is <b>inelastic</b> and a price increase <i>raises</i> revenue. A perfectly inelastic demand (E = 0) does not react to price at all.</p><p>Demand tends to be inelastic for necessities with few substitutes and elastic for goods with many close substitutes or luxury goods. The <b>cross-price elasticity</b> relates the change in demand for one good to a price change of another; it is positive for substitutes and negative for complements.</p>`,
qs:[
{q:'The price of a good rises by 10 % and the quantity demanded falls by 20 %. What is the price elasticity?',o:['−0.5 (inelastic)','−1 (unit elastic)','−2 (elastic)','−20 (elastic)'],a:2,e:'−20 % ÷ 10 % = −2; |E| > 1 ⇒ elastic.'},
{q:'Demand for a product is elastic. The firm lowers its price. What happens to revenue?',o:['It rises.','It falls.','It stays the same.','It cannot be determined from elasticity.'],a:0,e:'Elastic: quantity rises proportionally more than the price falls ⇒ revenue rises.'},
{q:'A cinema raises its ticket price from €50 to €55; weekly sales fall from 1,000 to 950 tickets. How does weekly revenue change?',o:['It falls by €2,250.','It stays at €50,000.','It rises by €2,250.','It rises by €5,000.'],a:2,e:'Before: 50 × 1,000 = 50,000. After: 55 × 950 = 52,250. Change = +2,250 (E = −5 % ÷ 10 % = −0.5, inelastic).'},
{q:'For which good is demand most likely to be inelastic?',o:['A particular brand of chocolate','Package holidays abroad','A life-saving prescription drug','A specific model of sports car'],a:2,e:'Necessity with few substitutes ⇒ inelastic.'},
{q:'How is perfectly inelastic demand shown in a price–quantity diagram (price on the vertical axis)?',o:['As a horizontal line','As a vertical line','As a downward-sloping 45° line','As an upward-sloping line'],a:1,e:'Quantity is the same at every price ⇒ vertical line.'},
{q:'When the price of tea rises, demand for coffee increases. What does this imply?',o:['Cross-price elasticity is negative; the goods are complements.','Cross-price elasticity is positive; the goods are substitutes.','Coffee demand is perfectly inelastic.','Tea demand is elastic.'],a:1,e:'Price of one ↑, demand for the other ↑ ⇒ positive cross elasticity ⇒ substitutes.'}
]},
{id:'npv',title:'Time Value of Money',domain:'Finance / Business',text:`<p>Money available today is worth more than the same amount in the future because it can earn interest. With an interest rate r per year and compound interest, a present value PV grows in n years to the <b>future value</b></p><p style="text-align:center">FV = PV · (1 + r)<sup>n</sup></p><p>Conversely, a future payment is <b>discounted</b> to today: PV = FV ÷ (1 + r)<sup>n</sup>. With <b>simple interest</b>, interest is only paid on the original amount: FV = PV · (1 + r·n).</p><p>Investment decisions are often based on the <b>net present value</b> (NPV): all future cash flows are discounted to today and the initial investment I<sub>0</sub> is subtracted:</p><p style="text-align:center">NPV = −I<sub>0</sub> + CF<sub>1</sub>/(1+r) + CF<sub>2</sub>/(1+r)² + …</p><p>A project with a positive NPV earns more than the required rate r. The rate at which NPV equals zero is called the <b>internal rate of return</b> (IRR).</p>`,
qs:[
{q:'€1,000 is invested at 10 % compound interest for 2 years. What is the future value?',o:['€1,100','€1,200','€1,210','€1,331'],a:2,e:'1,000 · 1.1² = 1,000 · 1.21 = 1,210.'},
{q:'What is the present value of €1,210 paid in 2 years at a rate of 10 %?',o:['€968','€1,000','€1,089','€1,100'],a:1,e:'1,210 ÷ 1.21 = 1,000.'},
{q:'A project costs €1,000 today and pays €550 after one year and €605 after two years. With r = 10 %, what is the NPV?',o:['−€155','€0','€155','€1,155'],a:1,e:'550/1.1 = 500; 605/1.21 = 500; NPV = −1,000 + 500 + 500 = 0.'},
{q:'The required rate of return for a project with only positive future cash flows increases. What happens to its NPV?',o:['It increases.','It decreases.','It is unchanged.','It becomes exactly zero.'],a:1,e:'Higher discount rate ⇒ future cash flows are worth less today ⇒ NPV falls.'},
{q:'€1,000 is invested for 3 years at 10 %. By how much does the compound-interest result exceed the simple-interest result?',o:['€0','€10','€31','€331'],a:2,e:'Compound: 1,000 · 1.1³ = 1,331. Simple: 1,000 · 1.3 = 1,300. Difference = 31.'},
{q:'What does an NPV of exactly zero at a rate of 8 % mean?',o:['The project loses 8 % per year.','The project\'s internal rate of return is 8 %.','The project pays back no money.','The project should always be rejected.'],a:1,e:'By definition, IRR is the rate where NPV = 0.'}
]},
{id:'ohm',title:'Simple Electric Circuits',domain:'Physics / Engineering',text:`<p>In a simple circuit, the voltage U (volts, V), current I (amperes, A) and resistance R (ohms, Ω) are linked by <b>Ohm's law</b>: U = R · I.</p><p>For resistors connected <b>in series</b>, the same current flows through all of them and the total resistance is the sum: R = R<sub>1</sub> + R<sub>2</sub> + …. The voltage divides in proportion to the resistances.</p><p>For resistors connected <b>in parallel</b>, all have the same voltage and the currents add up. The total resistance follows 1/R = 1/R<sub>1</sub> + 1/R<sub>2</sub> + …, so it is always smaller than the smallest individual resistance.</p><p>The electrical <b>power</b> is P = U · I (watts, W). Using Ohm's law it can also be written as P = I² · R or P = U² / R.</p>`,
qs:[
{q:'A voltage of 12 V is applied to a 4 Ω resistor. What current flows?',o:['0.33 A','3 A','16 A','48 A'],a:1,e:'I = U/R = 12/4 = 3 A.'},
{q:'Resistors of 2 Ω and 4 Ω are connected in series to 12 V. What is the voltage across the 4 Ω resistor?',o:['4 V','6 V','8 V','12 V'],a:2,e:'R = 6 Ω ⇒ I = 2 A; U₄ = 4 · 2 = 8 V.'},
{q:'What is the total resistance of 6 Ω and 3 Ω connected in parallel?',o:['2 Ω','4.5 Ω','9 Ω','18 Ω'],a:0,e:'1/R = 1/6 + 1/3 = 3/6 ⇒ R = 2 Ω.'},
{q:'A device draws 3 A from a 12 V source. What is its power?',o:['4 W','15 W','36 W','144 W'],a:2,e:'P = U · I = 12 · 3 = 36 W.'},
{q:'A second identical lamp is connected in parallel to a lamp on a fixed-voltage source. What happens to the total current drawn from the source?',o:['It halves.','It stays the same.','It doubles.','It quadruples.'],a:2,e:'Each lamp has the same voltage and draws the same current; currents add ⇒ total doubles.'},
{q:'The voltage stays constant while the resistance of a heater is doubled. What happens to the heating power?',o:['It doubles.','It halves.','It quadruples.','It stays the same.'],a:1,e:'P = U²/R: doubling R halves P.'}
]},
{id:'kinematics',title:'Motion with Constant Acceleration',domain:'Physics',text:`<p>For motion that starts from rest with constant acceleration a, the velocity and distance after time t are:</p><p style="text-align:center">v = a · t &nbsp;&nbsp;&nbsp;&nbsp; s = ½ · a · t²</p><p>Combining both gives v² = 2 · a · s. For motion at constant velocity, s = v · t.</p><p>Objects falling freely near the Earth's surface (air resistance neglected) accelerate with g ≈ 10 m/s², regardless of their mass.</p><p>The same equations describe braking: a vehicle with speed v that decelerates at a constant rate a needs the braking distance s = v² / (2a). Speeds are converted with 1 m/s = 3.6 km/h.</p>`,
qs:[
{q:'A car starts from rest and accelerates at 2 m/s² for 5 s. What is its speed?',o:['2.5 m/s','7 m/s','10 m/s','25 m/s'],a:2,e:'v = a·t = 2 · 5 = 10 m/s.'},
{q:'How far does the car travel in these 5 seconds?',o:['10 m','25 m','50 m','100 m'],a:1,e:'s = ½ · 2 · 5² = 25 m.'},
{q:'A stone is dropped from a height of 45 m. How long does it take to reach the ground?',o:['2 s','3 s','4.5 s','9 s'],a:1,e:'45 = ½ · 10 · t² ⇒ t² = 9 ⇒ t = 3 s.'},
{q:'With what speed does the stone hit the ground?',o:['15 m/s','30 m/s','45 m/s','90 m/s'],a:1,e:'v = g·t = 10 · 3 = 30 m/s (check: v² = 2·10·45 = 900).'},
{q:'A driver doubles her speed. With the same deceleration, how does the braking distance change?',o:['It stays the same.','It doubles.','It triples.','It quadruples.'],a:3,e:'s = v²/(2a): speed ×2 ⇒ distance ×4.'},
{q:'A heavy and a light ball are dropped simultaneously from the same height in a vacuum. Which statement is correct?',o:['The heavy ball lands first.','The light ball lands first.','Both land at the same time.','It depends on the height.'],a:2,e:'Free-fall acceleration does not depend on mass.'}
]},
{id:'gas',title:'The Ideal Gas Law',domain:'Physics / Chemistry',text:`<p>For an ideal gas, pressure p, volume V, amount of substance n and absolute temperature T are related by</p><p style="text-align:center">p · V = n · R · T</p><p>where R is the universal gas constant. Temperatures must be given in kelvin: T[K] = θ[°C] + 273 (rounded).</p><p>Special cases follow when some quantities are held constant. At constant temperature (<b>Boyle–Mariotte</b>), p · V is constant. At constant pressure (<b>Charles</b>), V is proportional to T. At constant volume (<b>Gay-Lussac</b>), p is proportional to T.</p>`,
qs:[
{q:'At constant temperature, the pressure on a gas is doubled. What happens to its volume?',o:['It doubles.','It halves.','It quadruples.','It stays the same.'],a:1,e:'p·V constant ⇒ p ×2 ⇒ V ÷2.'},
{q:'A sealed, rigid container is heated from 300 K to 600 K. What happens to the pressure?',o:['It halves.','It stays the same.','It doubles.','It increases by 300 %.'],a:2,e:'Constant V: p ∝ T; T doubles ⇒ p doubles (an increase of 100 %).'},
{q:'What is 27 °C in kelvin (rounded)?',o:['−246 K','27 K','246 K','300 K'],a:3,e:'27 + 273 = 300 K.'},
{q:'At constant pressure, 2 litres of gas at 300 K are heated to 450 K. What is the new volume?',o:['1.33 L','3 L','4 L','4.5 L'],a:1,e:'V ∝ T: 2 · 450/300 = 3 L.'},
{q:'A gas is heated at constant volume from 10 °C to 20 °C. Which statement is correct?',o:['The pressure doubles.','The pressure rises by about 3.5 %.','The pressure halves.','The pressure is unchanged.'],a:1,e:'Use kelvin: 283 K → 293 K; ratio ≈ 1.035. Doubling °C is not doubling T.'},
{q:'At constant temperature and volume, twice as many gas molecules are pumped into a container. What happens to the pressure?',o:['It doubles.','It halves.','It stays the same.','It quadruples.'],a:0,e:'p = nRT/V ⇒ p ∝ n.'}
]},
{id:'ph',title:'Acids, Bases and the pH Scale',domain:'Chemistry',text:`<p>The acidity of an aqueous solution is expressed by its <b>pH value</b>, defined as the negative decimal logarithm of the hydrogen-ion concentration (in mol/L):</p><p style="text-align:center">pH = −log<sub>10</sub>[H<sup>+</sup>]</p><p>A decrease of one pH unit therefore means a tenfold increase in [H<sup>+</sup>]. At 25 °C, pure water has pH 7 (neutral); solutions with pH &lt; 7 are acidic, those with pH &gt; 7 basic. The analogous quantity for hydroxide ions is pOH, and at 25 °C: pH + pOH = 14.</p><p>When an acid reacts with a base, a salt and water are formed (<b>neutralisation</b>). Diluting a strong acid with water lowers [H<sup>+</sup>] and raises the pH toward 7.</p>`,
qs:[
{q:'A solution has [H⁺] = 10⁻³ mol/L. What is its pH?',o:['−3','0.001','3','11'],a:2,e:'pH = −log(10⁻³) = 3.'},
{q:'How many times higher is [H⁺] at pH 2 than at pH 5?',o:['3 times','30 times','100 times','1,000 times'],a:3,e:'Difference of 3 units ⇒ 10³ = 1,000.'},
{q:'A strong acid with pH 2 is diluted tenfold with water. What is the new pH (approximately)?',o:['1','2','3','20'],a:2,e:'[H⁺] ÷ 10 ⇒ pH + 1 = 3.'},
{q:'A solution has pH 9 at 25 °C. Which statement is correct?',o:['It is acidic.','It is neutral.','It is basic.','Its pOH is 9.'],a:2,e:'pH > 7 ⇒ basic; pOH = 14 − 9 = 5.'},
{q:'What is the pOH of a solution with pH 4 at 25 °C?',o:['4','7','10','14'],a:2,e:'pOH = 14 − 4 = 10.'},
{q:'What are the products of a neutralisation reaction?',o:['An acid and a base','A salt and water','Hydrogen and oxygen','Only water'],a:1,e:'Acid + base → salt + water.'}
]},
{id:'enzyme',title:'Enzyme Kinetics',domain:'Biology / Biochemistry',text:`<p>Enzymes speed up chemical reactions. The reaction rate v depends on the substrate concentration [S] as described by the <b>Michaelis–Menten equation</b>:</p><p style="text-align:center">v = V<sub>max</sub> · [S] ÷ (K<sub>m</sub> + [S])</p><p>V<sub>max</sub> is the maximum rate reached when all enzyme molecules are saturated with substrate. The <b>Michaelis constant</b> K<sub>m</sub> is the substrate concentration at which the rate is half of V<sub>max</sub>. A small K<sub>m</sub> means that the enzyme reaches half its maximum rate already at low substrate concentrations — it has a high <b>affinity</b> for its substrate.</p><p>A <b>competitive inhibitor</b> resembles the substrate and competes for the active site. It raises the apparent K<sub>m</sub>, but at very high substrate concentrations it is outcompeted, so V<sub>max</sub> is unchanged.</p>`,
qs:[
{q:'What is the reaction rate when [S] equals Kₘ?',o:['0','Vmax/4','Vmax/2','Vmax'],a:2,e:'v = Vmax·Kₘ/(2Kₘ) = Vmax/2.'},
{q:'Vmax = 100 units, Kₘ = 2 mM, [S] = 6 mM. What is v?',o:['25 units','50 units','75 units','300 units'],a:2,e:'v = 100 · 6/(2 + 6) = 600/8 = 75.'},
{q:'What happens to v when [S] becomes very much larger than Kₘ?',o:['v approaches 0.','v approaches Vmax.','v increases without limit.','v equals Kₘ.'],a:1,e:'Kₘ + [S] ≈ [S] ⇒ v ≈ Vmax (saturation).'},
{q:'Enzyme X has Kₘ = 0.1 mM, enzyme Y has Kₘ = 5 mM for the same substrate. Which statement is correct?',o:['X has the higher affinity.','Y has the higher affinity.','Both have the same affinity.','X must have the higher Vmax.'],a:0,e:'Smaller Kₘ ⇒ higher affinity. Kₘ says nothing about Vmax.'},
{q:'How does a competitive inhibitor change the kinetic parameters?',o:['Kₘ ↑, Vmax unchanged','Kₘ unchanged, Vmax ↓','Kₘ ↓, Vmax ↓','Both unchanged'],a:0,e:'Stated in the text: apparent Kₘ rises, Vmax is unchanged.'},
{q:'At substrate concentrations far below Kₘ, how does v depend on [S]?',o:['v is constant.','v is roughly proportional to [S].','v decreases as [S] increases.','v is proportional to [S]².'],a:1,e:'Kₘ + [S] ≈ Kₘ ⇒ v ≈ (Vmax/Kₘ)·[S], a linear relation.'}
]},
{id:'bigo',title:'Efficiency of Algorithms',domain:'Computer Science',text:`<p>The efficiency of an algorithm is described with <b>Big-O notation</b>, which states how the number of steps grows with the input size n, ignoring constant factors.</p><table><tr><th>Class</th><th>Example</th></tr><tr><td>O(log n)</td><td>Binary search in a <i>sorted</i> list: each comparison halves the remaining search range.</td></tr><tr><td>O(n)</td><td>Linear search: check the elements one after another.</td></tr><tr><td>O(n log n)</td><td>Efficient sorting (e.g. merge sort).</td></tr><tr><td>O(n²)</td><td>Simple sorting (e.g. bubble sort); two nested loops over the input.</td></tr><tr><td>O(2ⁿ)</td><td>Trying all subsets of a set.</td></tr></table><p>For an O(n²) algorithm, tripling n multiplies the running time by about 3² = 9.</p>`,
qs:[
{q:'About how many comparisons does binary search need in the worst case for a sorted list of 1,024 elements?',o:['about 10','about 32','about 512','about 1,024'],a:0,e:'2¹⁰ = 1,024 ⇒ about log₂(1,024) = 10 halvings.'},
{q:'Which requirement must be met for binary search to work?',o:['The list must contain only numbers.','The list must be sorted.','The list must have an even length.','The list must not contain duplicates.'],a:1,e:'Halving only works if the order tells you which half to discard.'},
{q:'An O(n²) algorithm needs 2 seconds for n = 1,000. About how long does it need for n = 3,000?',o:['6 s','9 s','18 s','54 s'],a:2,e:'3² = 9 times longer: 2 · 9 = 18 s.'},
{q:'Which complexity class grows fastest for large n?',o:['O(n²)','O(n log n)','O(2ⁿ)','O(n)'],a:2,e:'Exponential growth outpaces any polynomial.'},
{q:'Linear search is run on an unsorted list of 500 elements and the item is not in the list. How many comparisons are made?',o:['1','9','250','500'],a:3,e:'Every element must be checked before concluding it is absent.'},
{q:'Two nested loops each run from 1 to n and perform one operation per inner step. How many operations are performed for n = 20?',o:['40','200','400','2²⁰'],a:2,e:'n · n = 20 · 20 = 400.'}
]},
{id:'binary',title:'Number Systems and Logic Operations',domain:'Computer Science / Engineering',text:`<p>Computers represent numbers in the <b>binary</b> system (base 2). Each position has a place value that is a power of 2: from right to left 1, 2, 4, 8, 16, …. For example, 1101₂ = 8 + 4 + 0 + 1 = 13. The <b>hexadecimal</b> system (base 16) uses the digits 0–9 and A–F (A = 10 … F = 15); each hex digit corresponds to four binary digits (bits).</p><p>Bitwise logic operations compare two numbers position by position:</p><table><tr><th>Operation</th><th>Result bit is 1 if …</th></tr><tr><td>AND</td><td>both bits are 1</td></tr><tr><td>OR</td><td>at least one bit is 1</td></tr><tr><td>XOR</td><td>exactly one bit is 1</td></tr></table><p>With k bits, 2<sup>k</sup> different values can be represented.</p>`,
qs:[
{q:'What is the decimal value of 1011₂?',o:['9','11','13','1011'],a:1,e:'8 + 0 + 2 + 1 = 11.'},
{q:'What is 26 in binary?',o:['10110','11001','11010','11100'],a:2,e:'26 = 16 + 8 + 2 ⇒ 11010.'},
{q:'What is the decimal value of the hexadecimal number 2F?',o:['29','31','47','215'],a:2,e:'2 · 16 + 15 = 47.'},
{q:'What is 1100 AND 1010?',o:['1000','1110','0110','0010'],a:0,e:'Only the leftmost position has 1 in both.'},
{q:'What is 1100 XOR 1010?',o:['1000','1110','0110','0001'],a:2,e:'Positions differ at the 2nd and 3rd bit ⇒ 0110.'},
{q:'How many different values can be stored in one byte (8 bits)?',o:['8','16','128','256'],a:3,e:'2⁸ = 256.'}
]},
{id:'survey',title:'Sampling and Bias in Social Research',domain:'Social Sciences',text:`<p>Surveys rarely question an entire population; instead they use a <b>sample</b>. In a <b>simple random sample</b>, every member of the population has the same chance of being selected. In a <b>stratified sample</b>, the population is first divided into groups (strata, e.g. age groups) and random samples are drawn from each group.</p><p>Results can be distorted by <b>bias</b>. <i>Selection bias</i> occurs when the sample systematically differs from the population, for example when participants choose themselves (self-selection). <i>Non-response bias</i> occurs when those who do not answer differ from those who do. <i>Response bias</i> can be caused by leading question wording.</p><p>The random sampling error shrinks with sample size n: the <b>margin of error</b> is roughly proportional to 1/√n. A measurement is <b>reliable</b> if it gives consistent results when repeated and <b>valid</b> if it measures what it is supposed to measure. Finally, a correlation between two variables does not prove causation; a third variable (a <b>confounder</b>) may influence both.</p>`,
qs:[
{q:'A news website asks its visitors to vote in an online poll on a political issue. Which problem is most likely?',o:['Non-response bias only','Self-selection bias','Stratification error','No bias, since many people vote'],a:1,e:'Participants choose themselves and are not representative of the population.'},
{q:'A researcher wants to halve the margin of error of a survey. By what factor must the sample size increase?',o:['2','4','8','It cannot be reduced.'],a:1,e:'Error ∝ 1/√n: to halve it, √n must double ⇒ n × 4.'},
{q:'Which procedure describes a stratified sample?',o:['Asking the first 100 people who pass by','Dividing the population into age groups and drawing randomly from each group','Asking participants to recruit their friends','Surveying only volunteers'],a:1,e:'Groups (strata) first, then random selection within each.'},
{q:'The question "Don\'t you agree that the new park is a waste of money?" mainly risks which distortion?',o:['Response bias caused by leading wording','Non-response bias','Sampling error','Low reliability of the scale'],a:0,e:'The wording pushes respondents toward a particular answer.'},
{q:'Ice-cream sales and drowning accidents are positively correlated. What is the best explanation?',o:['Eating ice cream causes drowning.','Drowning accidents increase ice-cream sales.','A third variable such as hot weather influences both.','The correlation must be a calculation error.'],a:2,e:'A confounder (summer temperature) drives both.'},
{q:'A bathroom scale always shows exactly 2 kg too much. How can it be described?',o:['Valid and reliable','Reliable but not valid','Valid but not reliable','Neither valid nor reliable'],a:1,e:'Consistent results (reliable) but systematically wrong (not valid).'}
]},
{id:'game',title:'Strategic Decisions: Game Theory',domain:'Economics',text:`<p>Game theory analyses situations in which the outcome for each participant depends on the decisions of others. A <b>dominant strategy</b> is one that yields a higher payoff than any alternative, whatever the other player does. A <b>Nash equilibrium</b> is a combination of strategies in which no player can improve by changing only their own strategy. An outcome is <b>Pareto-efficient</b> if no player can be made better off without making another worse off.</p><p>Two firms, A and B, each decide whether to set a <i>High</i> or <i>Low</i> price. The table shows annual profits in € million as (A, B):</p><table><tr><th></th><th>B: High</th><th>B: Low</th></tr><tr><th>A: High</th><td>(10, 10)</td><td>(2, 12)</td></tr><tr><th>A: Low</th><td>(12, 2)</td><td>(4, 4)</td></tr></table><p>If the game is repeated many times, firms may be able to sustain cooperation, e.g. by the <i>tit-for-tat</i> strategy (copy the opponent's previous move).</p>`,
qs:[
{q:'Does firm A have a dominant strategy?',o:['Yes, High','Yes, Low','No','Only if B chooses High'],a:1,e:'If B High: Low 12 > High 10. If B Low: Low 4 > High 2 ⇒ Low is always better.'},
{q:'Which combination is the Nash equilibrium?',o:['(High, High)','(High, Low)','(Low, High)','(Low, Low)'],a:3,e:'Both have Low as dominant strategy; neither gains by switching alone from (Low, Low).'},
{q:'Which outcome makes both firms better off than the equilibrium?',o:['(High, High)','(High, Low)','(Low, High)','None'],a:0,e:'(10, 10) beats (4, 4) for both.'},
{q:'What is the combined profit of both firms in the equilibrium?',o:['€8 million','€14 million','€20 million','€24 million'],a:0,e:'4 + 4 = 8.'},
{q:'Why can repeated interaction help the firms reach (High, High)?',o:['Because payoffs increase each round','Because a deviation today can be punished in later rounds','Because dominant strategies disappear','Because firms are forced by law to cooperate'],a:1,e:'Future retaliation (e.g. tit-for-tat) makes deviating less attractive.'},
{q:'Suppose the payoff for (Low, Low) changes to (1, 1); everything else stays the same. Which statement is correct?',o:['Low is still dominant for A.','High is now dominant for A.','A no longer has a dominant strategy.','(Low, Low) remains the only Nash equilibrium.'],a:2,e:'If B High: A prefers Low (12 > 10). If B Low: A prefers High (2 > 1). Best reply depends on B ⇒ no dominant strategy.'}
]},
{id:'regression',title:'Correlation and Linear Regression',domain:'Statistics / Social Sciences',text:`<p>The <b>correlation coefficient</b> r measures the strength and direction of a linear relationship between two variables. It lies between −1 and +1: values near ±1 indicate a strong linear relationship, values near 0 a weak one. In simple linear regression, the <b>coefficient of determination</b> R² = r² gives the share of the variance in y that is explained by x.</p><p>A <b>regression line</b> ŷ = a + b·x predicts y from x. The slope b states by how much y changes on average when x increases by one unit; the intercept a is the predicted value for x = 0. Predictions far outside the range of the observed data (<b>extrapolation</b>) are unreliable.</p><p>A study of students found the following relation between weekly study hours (x, observed range 0–15 h) and exam score (y, maximum 100 points):</p><p style="text-align:center">ŷ = 40 + 5·x, &nbsp;&nbsp; r = 0.8</p>`,
qs:[
{q:'What score does the model predict for a student who studies 6 hours per week?',o:['46','60','70','300'],a:2,e:'40 + 5 · 6 = 70.'},
{q:'How is the slope of 5 interpreted?',o:['Students study 5 hours on average.','Each additional study hour is associated with 5 more points on average.','5 % of the variance is explained.','The minimum score is 5.'],a:1,e:'Slope = average change in y per unit of x.'},
{q:'What share of the variance in exam scores is explained by study time?',o:['8 %','40 %','64 %','80 %'],a:2,e:'R² = 0.8² = 0.64.'},
{q:'Why is it problematic to use the model for a student who studies 30 hours?',o:['The predicted score of 190 is impossible; this is an extrapolation beyond the data.','Because r is below 1.','Because the intercept is 40.','There is no problem.'],a:0,e:'30 h is outside the observed 0–15 h range, and 40 + 150 = 190 exceeds the maximum of 100.'},
{q:'In another study, r = −0.9. What does this mean?',o:['A weak negative relationship','A strong negative linear relationship','No relationship','A strong positive relationship'],a:1,e:'Magnitude 0.9 = strong; sign negative.'},
{q:'All exam scores are raised by 10 bonus points. How does the regression line change?',o:['Slope +10','Intercept +10, slope unchanged','Both unchanged','r increases'],a:1,e:'Shifting all y-values moves the line up without changing its slope (r unchanged too).'}
]},
{id:'market',title:'Market Equilibrium',domain:'Economics',text:`<p>In a competitive market, the <b>equilibrium price</b> is the price at which the quantity demanded equals the quantity supplied. For a certain product, demand and supply (quantity Q in thousand units, price P in €) are:</p><p style="text-align:center">Demand: Q<sub>d</sub> = 100 − 2P &nbsp;&nbsp;&nbsp;&nbsp; Supply: Q<sub>s</sub> = 20 + 2P</p><p>A government can intervene in the market. A <b>maximum price</b> (price ceiling) set below the equilibrium price leads to excess demand (shortage). A <b>minimum price</b> (price floor) set above the equilibrium price leads to excess supply (surplus). A <b>tax</b> levied on producers raises their costs, which shifts the supply curve to the left (upwards).</p><p>If consumers want to buy more at every price (e.g. because incomes rise), the demand curve shifts to the right.</p>`,
qs:[
{q:'What is the equilibrium price?',o:['€15','€20','€25','€40'],a:1,e:'100 − 2P = 20 + 2P ⇒ 80 = 4P ⇒ P = 20.'},
{q:'What is the equilibrium quantity?',o:['40 thousand','50 thousand','60 thousand','80 thousand'],a:2,e:'Q = 100 − 2 · 20 = 60.'},
{q:'The government sets a maximum price of €15. What is the result?',o:['A surplus of 20 thousand units','A shortage of 20 thousand units','A shortage of 10 thousand units','No effect'],a:1,e:'Qd = 70, Qs = 50 ⇒ excess demand 20.'},
{q:'A tax on producers is introduced. What happens (ceteris paribus)?',o:['Price falls, quantity rises.','Price rises, quantity falls.','Price and quantity both rise.','Nothing changes.'],a:1,e:'Supply shifts left ⇒ higher price, lower quantity.'},
{q:'A minimum price is set at €30. What is the consequence?',o:['Shortage','Surplus','Equilibrium','The minimum price has no effect'],a:1,e:'Above equilibrium: Qs = 80 > Qd = 40 ⇒ surplus of 40.'},
{q:'Demand changes to Qd = 120 − 2P. What is the new equilibrium?',o:['P = 20, Q = 60','P = 25, Q = 70','P = 30, Q = 60','P = 25, Q = 80'],a:1,e:'120 − 2P = 20 + 2P ⇒ P = 25; Q = 20 + 50 = 70.'}
]},
{id:'breakeven',title:'Break-Even Analysis',domain:'Business Administration',text:`<p>Costs of a company are split into <b>fixed costs</b> (independent of output, e.g. rent) and <b>variable costs</b> (rising with each unit produced, e.g. material). The <b>contribution margin</b> per unit is the selling price minus the variable cost per unit; it is the amount each unit contributes to covering fixed costs and then to profit.</p><p>The <b>break-even point</b> (BEP) is the output at which total revenue equals total costs, i.e. profit is zero:</p><p style="text-align:center">BEP (units) = fixed costs ÷ contribution margin per unit</p><p>As output increases, fixed costs are spread over more units, so the fixed cost per unit falls (<i>fixed-cost degression</i>).</p><p>A small bakery has monthly fixed costs of €12,000. It sells a cake for €50; the variable cost per cake is €30.</p>`,
qs:[
{q:'What is the contribution margin per cake?',o:['€12','€20','€30','€80'],a:1,e:'50 − 30 = 20.'},
{q:'How many cakes must be sold per month to break even?',o:['240','400','600','1,200'],a:2,e:'12,000 ÷ 20 = 600.'},
{q:'What is the monthly profit when 1,000 cakes are sold?',o:['€8,000','€20,000','€38,000','€50,000'],a:0,e:'1,000 · 20 − 12,000 = 8,000.'},
{q:'The price rises to €60 (costs unchanged). What is the new break-even point?',o:['300 cakes','400 cakes','500 cakes','600 cakes'],a:1,e:'Margin = 30; 12,000 ÷ 30 = 400.'},
{q:'At a price of €50, how many cakes are needed for a profit of €4,000?',o:['700','800','900','1,000'],a:1,e:'(12,000 + 4,000) ÷ 20 = 800.'},
{q:'What happens to the fixed cost per cake when output increases from 600 to 1,200 cakes?',o:['It doubles from €20 to €40.','It halves from €20 to €10.','It stays at €20.','It becomes zero.'],a:1,e:'12,000/600 = 20; 12,000/1,200 = 10.'}
]},
{id:'heat',title:'Heat and Temperature',domain:'Physics / Engineering',text:`<p>The heat Q required to change the temperature of a body by ΔT is</p><p style="text-align:center">Q = m · c · ΔT</p><p>where m is the mass and c the <b>specific heat capacity</b> of the material. For water, c ≈ 4.2 kJ/(kg·K). A temperature difference of 1 K equals a difference of 1 °C. Materials with a lower specific heat capacity heat up faster when the same amount of energy is supplied.</p><p>When two amounts of the same liquid with different temperatures are mixed (no heat losses), the mixing temperature is the <b>mass-weighted mean</b>: T<sub>mix</sub> = (m<sub>1</sub>T<sub>1</sub> + m<sub>2</sub>T<sub>2</sub>) ÷ (m<sub>1</sub> + m<sub>2</sub>).</p><p>Power is energy per time: P = Q ÷ t, where 1 W = 1 J/s and 1 kW = 1 kJ/s.</p>`,
qs:[
{q:'How much heat is needed to warm 2 kg of water by 10 K?',o:['8.4 kJ','42 kJ','84 kJ','840 kJ'],a:2,e:'2 · 4.2 · 10 = 84 kJ.'},
{q:'1 kg of water at 20 °C is mixed with 1 kg of water at 60 °C. What is the mixing temperature?',o:['30 °C','40 °C','50 °C','80 °C'],a:1,e:'Equal masses ⇒ simple average: 40 °C.'},
{q:'3 kg of water at 20 °C are mixed with 1 kg at 60 °C. What is the mixing temperature?',o:['25 °C','30 °C','35 °C','40 °C'],a:1,e:'(3·20 + 1·60) ÷ 4 = 120 ÷ 4 = 30 °C.'},
{q:'A 2 kW kettle runs for 2 minutes without losses. By roughly how much does it warm 1 kg of water?',o:['about 5.7 K','about 29 K','about 57 K','about 240 K'],a:2,e:'Q = 2 kJ/s · 120 s = 240 kJ; ΔT = 240 ÷ 4.2 ≈ 57 K.'},
{q:'Equal masses of water and of oil (c ≈ 2 kJ/(kg·K)) receive the same amount of heat. Which statement is correct?',o:['Both warm by the same amount.','The water warms about twice as much.','The oil warms about twice as much.','The oil does not warm up.'],a:2,e:'ΔT = Q/(m·c): half the c ⇒ about twice the ΔT.'},
{q:'A heater delivers 84 kJ in 42 s. What is its power?',o:['0.5 kW','2 kW','3.5 kW','126 kW'],a:1,e:'84 kJ ÷ 42 s = 2 kJ/s = 2 kW.'}
]}
];
const PRACTICE_IDS=['stats','growth','elasticity','ohm','kinematics','ph','bigo','survey','regression','breakeven'];
const MOCK_SETS={mock1:['bayes','npv','gas','binary'],mock2:['enzyme','game','market','heat']};
